<a href="https://colab.research.google.com/github/aren4/Kambo/blob/main/Kambo_Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

long_df_merged = pd.read_csv('/content/drive/MyDrive/Kambo/Kambo_long_df_anonymized.csv')
pd.set_option('display.max_columns', None)
long_df_merged.shape
long_df_merged.head()

,Unnamed: 0,START DATE | STARTDATE,END DATE | ENDDATE,RESPONSE TYPE | STATUS,IP ADDRESS | IPADDRESS,PROGRESS,DURATION (IN SECONDS),FINISHED,RECORDED DATE | RECORDEDDATE,RESPONSE ID | RESPONSEID,RECIPIENT LAST NAME | RECIPIENTLASTNAME,RECIPIENT FIRST NAME | RECIPIENTFIRSTNAME,RECIPIENT EMAIL | RECIPIENTEMAIL,EXTERNAL DATA REFERENCE | EXTERNALREFERENCE,LOCATION LATITUDE | LOCATIONLATITUDE,LOCATION LONGITUDE | LOCATIONLONGITUDE,DISTRIBUTION CHANNEL | DISTRIBUTIONCHANNEL,USER LANGUAGE | USERLANGUAGE,WHAT IS THE NAME OF THE PRACTITIONER YOU WILL BE WORKING WITH? | GEN.1.,WHAT IS THE DATE OF YOUR 1ST SCHEDULED KAMBO SESSION? | GEN.2.,WHAT IS THE DATE OF YOUR 3RD SCHEDULED KAMBO SESSION? | GEN.3.,WHAT IS YOUR AGE? | DEMO.1.,WHAT BIOLOGICAL SEX WERE YOU ASSIGNED AT BIRTH? | DEMO.2.,WHAT GENDER DO YOU IDENTIFY WITH? - SELECTED CHOICE | DEMO.3.,WHAT GENDER DO YOU IDENTIFY WITH? - OTHER - TEXT | DEMO.3._7_TEXT,WHAT RACE DO YOU IDENTIFY AS? | DEMO.4.,WHAT IS YOUR HIGHEST LEVEL OF EDUCATION COMPLETED? | DEMO.5.,WHAT IS YOUR GROSS HOUSEHOLD INCOME? | DEMO.6.,"WHAT IS YOUR APPROXIMATE HEIGHT (FT, IN)? | DEMO.7.",WHAT IS YOUR APPROXIMATE WEIGHT (LBS)? | DEMO.8.,HAVE YOU BEEN DIAGNOSED WITH ANY MEDICAL CONDITIONS OR DISEASE? DO YOU CURRENTLY DEAL WITH THESE CONDITIONS OR HAVE YOU RECOVERED FROM THESE CONDITIONS? PLEASE EXPLAIN. | DEMO.9.,HAVE YOU BEEN DIAGNOSED WITH LYME DISEASE BY A LICENSED HEALTHCARE PROFESSIONAL? | DEMO.10.,HAVE YOU BEEN DIAGNOSED WITH POST-TREATMENT LYME SYNDROME BY A LICENSED HEALTHCARE PROFESSIONAL? | DEMO.11.,"PLEASE LIST ANY DRUGS, MEDICATIONS, OR SUPPLEMENTS YOU ARE CURRENTLY TAKING. | DEMO.12.","HAVE YOU EVER USED A PSYCHEDELIC SUBSTANCE SUCH AS LSD, PSILOCYBIN (MAGIC) MUSHROOMS, MESCALINE (PEYOTE), DMT, OR AYAHUASCA? | DEMO.13.",DO YOU USE CANNABIS? | DEMO.14.,WHAT ARE THE REASONS YOU HAVE SOUGHT OUT KAMBO? | DEMO.15.,PLEASE SELECT THE OPTION THAT REFLECTS HOW NERVOUS YOU ARE FEELING ABOUT YOUR UPCOMING KAMBO EXPERIENCES. | DEMO.16.,PLEASE SELECT THE OPTION THAT REFLECTS HOW EXCITED YOU ARE FEELING ABOUT YOUR UPCOMING KAMBO EXPERIENCES. | DEMO.17.,CLICK TO WRITE THE QUESTION TEXT - I COULD BE EXPERIENCING SOME EMOTION AND NOT BE CONSCIOUS OF IT UNTIL SOME TIME LATER | MAAS_1,"CLICK TO WRITE THE QUESTION TEXT - I BREAK OR SPILL THINGS BECAUSE OF CARELESSNESS, NOT PAYING ATTENTION, OR THINKING OF SOMETHING ELSE | MAAS_2",CLICK TO WRITE THE QUESTION TEXT - I FIND IT DIFFICULT TO STAY FOCUSED ON WHAT’S HAPPENING IN THE PRESENT | MAAS_3,CLICK TO WRITE THE QUESTION TEXT - I TEND TO WALK QUICKLY TO GET WHERE I’M GOING WITHOUT PAYING ATTENTION TO WHAT I EXPERIENCE ALONG THE WAY | MAAS_4,CLICK TO WRITE THE QUESTION TEXT - I TEND NOT TO NOTICE FEELINGS OF PHYSICAL TENSION OR DISCOMFORT UNTIL THEY REALLY GRAB MY ATTENTION | MAAS_5,CLICK TO WRITE THE QUESTION TEXT - I FORGET A PERSON’S NAME ALMOST AS SOON AS I’VE BEEN TOLD IT FOR THE FIRST TIME | MAAS_6,"CLICK TO WRITE THE QUESTION TEXT - IT SEEMS I AM “RUNNING ON AUTOMATIC,” WITHOUT MUCH AWARENESS OF WHAT I’M DOING | MAAS_7",CLICK TO WRITE THE QUESTION TEXT - I RUSH THROUGH ACTIVITIES WITHOUT BEING REALLY ATTENTIVE TO THEM | MAAS_8,CLICK TO WRITE THE QUESTION TEXT - I GET SO FOCUSED ON THE GOAL I WANT TO ACHIEVE THAT I LOSE TOUCH WITH WHAT I’M DOING RIGHT NOW TO GET THERE | MAAS_9,"CLICK TO WRITE THE QUESTION TEXT - I DO JOBS OR TASKS AUTOMATICALLY, WITHOUT BEING AWARE OF WHAT I'M DOING | MAAS_10","CLICK TO WRITE THE QUESTION TEXT - I FIND MYSELF LISTENING TO SOMEONE WITH ONE EAR, DOING SOMETHING ELSE AT THE SAME TIME | MAAS_11",CLICK TO WRITE THE QUESTION TEXT - I DRIVE PLACES ON ‘AUTOMATIC PILOT’ AND THEN WONDER WHY I WENT THERE | MAAS_12,CLICK TO WRITE THE QUESTION TEXT - I FIND MYSELF PREOCCUPIED WITH THE FUTURE OR THE PAST | MAAS_13,CLICK TO WRITE THE QUESTION TEXT - I FIND MYSELF DOING THINGS WITHOUT PAYING ATTENTION | MAAS_14,CLICK TO WRITE THE QUESTION TEXT - I SNACK WITHOUT BEING AWARE THAT I’M EATING | MAAS_15,"CLICK TO WRITE THE QUESTION TEXT - I AM NOT AFRAID TO VOICE MY OPINIONS, EVEN WHEN THEY ARE IN OPPOSITION TO THE OPINIONS OF MOST PEOPLE | RYFF_1","CLICK TO WRITE THE QUESTION TEXT - FOR ME, LIFE HAS BEEN A CONTINUOUS PROCESS OF LEARNING, CHANGING, AND GROWTH | RYFF_2","CLICK TO WRITE THE QUESTION TEXT - IN GENERAL, I FEEL I AM IN CHARGE OF THE SITUATION IN WHICH I LIVE | RYFF_3","CLICK TO WRITE THE QUESTION TEXT - PEOPLE WOULD DESCRIBE ME AS A GIVING PERSON, WILLING TO SHARE MY TIME WITH OTHERS | RYFF_4",CLICK TO WRITE THE QUESTION TEXT - I AM NOT INTERESTED IN ACTIVITIES THAT WILL EXPAND MY HORIZONS | RYFF_5,CLICK TO WRITE THE QUESTION TEXT - I ENJOY MAKING PLANS FOR THE FUTURE AND WORKING TO MAKE THEM A REALITY | RYFF_6,CLICK TO WRITE THE QUESTION TEXT - MOST PEOPLE SEE ME AS LOVING AND AFFECTIONATE | RYFF_7,CLICK TO WRITE THE QUESTION TEXT - IN MANY WAYS I FEEL DISAPPOINTED ABOUT MY ACHIEVEMENTS IN LIFE | RYFF_8,CLICK TO WRITE THE QUESTION TEXT - I LIVE LIFE ONE DAY AT A TIME AND DON'T REALLY THINK ABOUT THE FUTURE | RYFF_9,CLICK TO WRITE THE QUESTION TEXT - I TEND TO WORRY ABOUT WHAT OTHER PEOPLE THINK OF ME | RYFF_10,"CLICK TO WRITE THE QUESTION TEXT - WHEN I LOOK AT THE STORY OF MY LIFE, I AM PLEASED WITH HOW THINGS HAVE TURNED OUT | RYFF_11",CLICK TO WRITE THE QUESTION TEXT - I HAVE DIFFICULTY ARRANGING MY LIFE IN A WAY THAT IS SATISFYING TO ME | RYFF_12,CLICK TO WRITE THE QUESTION TEXT - MY DECISIONS ARE NOT USUALLY INFLUENCED BY WHAT EVERYONE ELSE IS DOING | RYFF_13,CLICK TO WRITE THE QUESTION TEXT - I GAVE UP TRYING TO MAKE BIG IMPROVEMENTS OR CHANGES IN MY LIFE A LONG TIME AGO | RYFF_14,CLICK TO WRITE THE QUESTION TEXT - THE DEMANDS OF EVERYDAY LIFE OFTEN GET ME DOWN | RYFF_15,CLICK TO WRITE THE QUESTION TEXT - I HAVE NOT EXPERIENCED MANY WARM AND TRUSTING RELATIONSHIPS WITH OTHERS | RYFF_16,CLICK TO WRITE THE QUESTION TEXT - I THINK IT IS IMPORTANT TO HAVE NEW EXPERIENCES THAT CHALLENGE HOW YOU THINK ABOUT YOURSELF AND THE WORLD | RYFF_17,CLICK TO WRITE THE QUESTION TEXT - MAINTAINING CLOSE RELATIONSHIPS HAS BEEN DIFFICULT AND FRUSTRATING FOR ME | RYFF_18,CLICK TO WRITE THE QUESTION TEXT - MY ATTITUDE ABOUT MYSELF IS PROBABLY NOT AS POSITIVE AS MOST PEOPLE FEEL ABOUT THEMSELVES | RYFF_19,CLICK TO WRITE THE QUESTION TEXT - I HAVE A SENSE OF DIRECTION AND PURPOSE IN LIFE | RYFF_20,"CLICK TO WRITE THE QUESTION TEXT - I JUDGE MYSELF BY WHAT I THINK IS IMPORTANT, NOT BY THE VALUES OF WHAT OTHERS THINK IS IMPORTANT | RYFF_21","CLICK TO WRITE THE QUESTION TEXT - IN GENERAL, I FEEL CONFIDENT AND POSITIVE ABOUT MYSELF | RYFF_22",CLICK TO WRITE THE QUESTION TEXT - I HAVE BEEN ABLE TO BUILD A LIVING ENVIRONMENT AND A LIFESTYLE FOR MYSELF THAT IS MUCH TO MY LIKING | RYFF_23,CLICK TO WRITE THE QUESTION TEXT - I TEND TO BE INFLUENCED BY PEOPLE WITH STRONG OPINIONS | RYFF_24,CLICK TO WRITE THE QUESTION TEXT - I DO NOT ENJOY BEING IN NEW SITUATIONS THAT REQUIRE ME TO CHANGE MY OLD FAMILIAR WAYS OF DOING THINGS | RYFF_25,CLICK TO WRITE THE QUESTION TEXT - I DO NOT FIT VERY WELL WITH THE PEOPLE AND THE COMMUNITY AROUND ME | RYFF_26,"CLICK TO WRITE THE QUESTION TEXT - I KNOW THAT I CAN TRUST MY FRIENDS, AND THEY KNOW THEY CAN TRUST ME | RYFF_27","CLICK TO WRITE THE QUESTION TEXT - WHEN I THINK ABOUT IT, I HAVEN’T REALLY IMPROVED MUCH AS A PERSON OVER THE YEARS | RYFF_28","CLICK TO WRITE THE QUESTION TEXT - SOME PEOPLE WANDER AIMLESSLY THROUGH LIFE, BUT I AM NOT ONE OF THEM | RYFF_29",CLICK TO WRITE THE QUESTION TEXT - I OFTEN FEEL LONELY BECAUSE I HAVE FEW CLOSE FRIENDS WITH WHOM TO SHARE MY CONCERNS | RYFF_30,"CLICK TO WRITE THE QUESTION TEXT - WHEN I COMPARE MYSELF TO FRIENDS AND ACQUAINTANCES, IT MAKES ME FEEL GOOD ABOUT WHO I AM | RYFF_31",CLICK TO WRITE THE QUESTION TEXT - I DON’T HAVE A GOOD SENSE OF WHAT IT IS I’M TRYING TO ACCOMPLISH IN LIFE | RYFF_32,CLICK TO WRITE THE QUESTION TEXT - I SOMETIMES FEEL AS IF I'VE DONE ALL THERE IS TO DO IN LIFE | RYFF_33,CLICK TO WRITE THE QUESTION TEXT - I FEEL LIKE MANY OF THE PEOPLE I KNOW HAVE GOTTEN MORE OUT OF LIFE THAN I HAVE | RYFF_34,"CLICK TO WRITE THE QUESTION TEXT - I HAVE CONFIDENCE IN MY OPINIONS, EVEN IF THEY ARE CONTRARY TO THE GENERAL CONSENSUS | RYFF_35",CLICK TO WRITE THE QUESTION TEXT - I AM QUITE GOOD AT MANAGING THE MANY RESPONSIBILITIES OF MY DAILY LIFE | RYFF_36,CLICK TO WRITE THE QUESTION TEXT - I HAVE THE SENSE THAT I HAVE DEVELOPED A LOT AS A PERSON OVER TIME | RYFF_37,CLICK TO WRITE THE QUESTION TEXT - I ENJOY PERSONAL AND MUTUAL CONVERSATIONS WITH FAMILY MEMBERS AND FRIENDS | RYFF_38,CLICK TO WRITE THE QUESTION TEXT - MY DAILY ACTIVITIES OFTEN SEEM TRIVIAL AND UNIMPORTANT TO ME | RYFF_39,CLICK TO WRITE THE QUESTION TEXT - I LIKE MOST PARTS OF MY PERSONALITY | RYFF_40,CLICK TO WRITE THE QUESTION TEXT - IT’S DIFFICULT FOR ME TO VOICE MY OWN OPINIONS ON CONTROVERSIAL MATTERS | RYFF_41,CLICK TO WRITE THE QUESTION TEXT - I OFTEN FEEL OVERWHELMED BY MY RESPONSIBILITIES | RYFF_42,CLICK TO WRITE THE QUESTION TEXT - I FEEL FIT | MFI_1,"CLICK TO WRITE THE QUESTION TEXT - PHYSICALLY, I FEEL ONLY ABLE TO DO A LITTLE | MFI_2",CLICK TO WRITE THE QUESTION TEXT - I FEEL VERY ACTIVE | MFI_3,CLICK TO WRITE THE QUESTION TEXT - I FEEL LIKE DOING ALL SORTS OF NICE THINGS | MFI_4,CLICK TO WRITE THE QUESTION TEXT - I FEEL TIRED | MFI_5,CLICK TO WRITE THE QUESTION TEXT - I THINK I DO A LOT IN A DAY | MFI_6,"CLICK TO WRITE THE QUESTION TEXT - WHEN I AM DOING SOMETHING, I CAN KEEP MY THOUGHTS ON IT | MFI_7",CLICK TO WRITE THE QUESTION TEXT - PHYSICALLY I CAN TAKE ON A LOT | MFI_8,CLICK TO WRITE THE QUESTION TEXT - I DREAD HAVING TO DO THINGS | MFI_9,CLICK TO WRITE THE QUESTION TEXT - I THINK I DO VERY LITTLE IN A DAY | MFI_10,CLICK TO WRITE THE QUESTION TEXT - I CAN CONCENTRATE WELL | MFI_11,CLICK TO WRITE THE QUESTION TEXT - I AM RESTED | MFI_12,CLICK TO WRITE THE QUESTION TEXT - IT TAKES A LOT OF EFFORT TO CONCENTRATE ON THINGS | MFI_13,CLICK TO WRITE THE QUESTION TEXT - PHYSICALLY I FEEL I AM IN A BAD CONDITION | MFI_14,CLICK TO WRITE THE QUESTION TEXT - I HAVE A LOT OF PLANS | MFI_15,CLICK TO WRITE THE QUESTION TEXT - I TIRE EASILY | MFI_16,CLICK TO WRITE THE QUESTION TEXT - I GET LITTLE DONE | MFI_17,CLICK TO WRITE THE QUESTION TEXT - I DON'T FEEL LIKE DOING ANYTHING | MFI_18,CLICK TO WRITE THE QUESTION TEXT - MY THOUGHTS EASILY WANDER | MFI_19,CLICK TO WRITE THE QUESTION TEXT - PHYSICALLY I FEEL I AM IN AN EXCELLENT CONDITION | MFI_20,FALLING ASLEEP: | IDS.1.,SLEEP DURING THE NIGHT: | IDS.2.,WAKING UP TOO EARLY: | IDS.3.,SLEEPING TOO MUCH: | IDS.4.,FEELING SAD: | IDS.5.,FEELING IRRITABLE: | IDS.6.,FEELING ANXIOUS OR TENSE: | IDS.7.,RESPONSE OF YOUR MOOD TO GOOD OR DESIRED EVENTS: | IDS.8.,MOOD IN RELATION TO THE TIME OF DAY: | IDS.9.,MY MOOD IS TYPICALLY WORSE IN THE... | IDS.9A.,IS YOUR MOOD VARIATION ATTRIBUTED TO ENVIRONMENT? | IDS.9B.,THE QUALITY OF YOUR MOOD: | IDS.10.,DECREASED APPETITE: | IDS.11.,INCREASED APPETITE: | IDS.12.,DECREASED WEIGHT (WITHIN THE LAST TWO WEEKS): | IDS.13.,INCREASED WEIGHT (WITHIN THE LAST TWO WEEKS): | IDS.14.,CONCENTRATION/DECISION MAKING: | IDS.15.,VIEW OF MYSELF: | IDS.16.,VIEW OF MY FUTURE | IDS.17.,THOUGHTS OF DEATH OR SUICIDE: | IDS.18.,GENERAL INTEREST: | IDS.19.,ENERGY LEVELS: | IDS.20.,CAPACITY FOR PLEASURE OR ENJOYMENT (EXCLUDING SEX): | IDS.21.,"INTEREST IN SEX (PLEASE RATE INTEREST, NOT ACTIVITY): | IDS.22.",FEELING SLOWED DOWN: | IDS.23.,FEELING RESTLESS: | IDS.24.,ACHES AND PAINS: | IDS.25.,OTHER BODILY SYMPTOMS: | IDS.26.,PANIC/PHOBIC SYMPTOMS: | IDS.27.,CONSTIPATION/DIARRHEA: | IDS.28.,INTERPERSONAL SENSITIVITY: | IDS.29.,LEADEN PARALYSIS/PHYSICAL ENERGY: | IDS.30.,"IN GENERAL, I CONSIDER MYSELF: | SHS.1","COMPARED WITH MOST OF MY PEERS, I CONSIDER MYSELF: | SHS.2","SOME PEOPLE ARE GENERALLY VERY HAPPY. THEY ENJOY LIFE REGARDLESS OF WHAT IS GOING ON, \r\nGETTING THE MOST OUT OF EVERYTHING. TO WHAT EXTENT DOES THIS CHARACTERIZATION DESCRIBE YOU? | SHS.3","SOME PEOPLE ARE GENERALLY NOT VERY HAPPY. ALTHOUGH THEY ARE NOT DEPRESSED, THEY NEVER \r\nSEEM AS HAPPY AS THEY MIGHT BE. TO WHAT EXTENT DOES THIS CHARACTERIZATION DESCRIBE YOU? | SHS.4","THROUGHOUT OUR LIVES, MOST OF US HAVE HAD PAIN FROM TIME TO TIME\n(SUCH AS MINOR HEADACHES, SPRAINS, AND TOOTHACHES). HAVE YOU HAD\nPAIN OTHER THAN THESE EVERYDAY KINDS OF PAIN DURING THE LAST WEEK? - SELECTED CHOICE | BPI.1.","THROUGHOUT OUR LIVES, MOST OF US HAVE HAD PAIN FROM TIME TO TIME\n(SUCH AS MINOR HEADACHES, SPRAINS, AND TOOTHACHES). HAVE YOU HAD\nPAIN OTHER THAN THESE EVERYDAY KINDS OF PAIN DURING THE LAST WEEK? - YES (PLEASE SPECIFY) - TEXT | BPI.1._1_TEXT",DID YOU TAKE PAIN MEDICATIONS IN THE LAST 7 DAYS? | BPI.1A.,I FEEL I HAVE HAD SOME PAIN THAT REQUIRES MEDICATION EACH AND EVERY DAY | BPI.1B.,PLEASE RATE YOUR PAIN ACCORDING TO THE FOLLOWING STATEMENTS: - PLEASE RATE YOUR PAIN BY FILLING IN THE ONE NUMBER THAT BEST DESCRIBES YOUR PAIN AT ITS WORST IN THE PAST 24 HOURS. | BPI.3._1,PLEASE RATE YOUR PAIN ACCORDING TO THE FOLLOWING STATEMENTS: - PLEASE RATE YOUR PAIN BY FILLING IN THE ONE NUMBER THAT BEST DESCRIBES YOUR PAIN AT ITS LEAST IN THE PAST 24 HOURS | BPI.3._2,PLEASE RATE YOUR PAIN ACCORDING TO THE FOLLOWING STATEMENTS: - PLEASE RATE YOUR PAIN BY FILLING IN THE ONE NUMBER THAT BEST DESCRIBES YOUR PAIN ON THE AVERAGE. | BPI.3._3,WHAT TREATMENTS OR MEDICATIONS ARE YOU RECEIVING FOR YOUR PAIN? | BPI.4.,"IN THE PAST 24 HOURS, HOW MUCH RELIEF HAVE PAIN TREATMENTS OR \nMEDICATIONS PROVIDED? PLEASE SELECT THE ONE PERCENTAGE THAT MOST\nSHOWS HOW MUCH RELIEF YOU HAVE RECEIVED. | BPI.5.","SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - GENERAL ACTIVITY | BPI.6._1","SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - MOOD | BPI.6._2","SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - WALKING ABILITY | BPI.6._3","SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - NORMAL WORK (INCLUDES BOTH WORK OUTSIDE THE HOME AND HOUSEWORK) | BPI.6._4","SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - RELATION WITH OTHER PEOPLE | BPI.6._5","SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - SLEEP | BPI.6._6","SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - ENJOYMENT OF LIFE | BPI.6._7",Phase,1.\tPLEASE BRIEFLY DESCRIBE YOUR EXPERIENCE IN THE KAMBO RITUAL: | QUAL.1.,2. WERE THERE SPECIFIC ASPECTS OF THE RITUAL THAT WERE PARTICULARLY VALUABLE? | QUAL.2.,3.\tWERE THERE SPECIFIC ASPECTS OF THE RITUAL THAT WERE PARTICULARLY CHALLENGING? | QUAL.3.,DID YOU EXPERIENCE ANY EMOTIONAL ELEMENTS OF THE KAMBO RITUAL? | QUAL.4.,5.\tDID YOU EXPERIENCE ANY SPIRITUAL ELEMENTS OF THE KAMBO RITUAL? | QUAL.5.,6.\tWHAT WERE THE REASONS YOU SOUGHT OUT KAMBO AND DID THE PROCESS SATISFY THEM? | QUAL 6.,"LOOKING BACK ON THE ENTIRETY OF YOUR SESSIONS, PLEASE RATE THE DEGREE TO WHICH AT ANY TIME DURING THAT SESSION YOU EXPERIENCED THE FOLLOWING PHENOMENA. ANSWER EACH QUESTION ACCORDING TO YOUR FEELINGS, THOUGHTS, AND EXPERIENCES AT THE TIME OF THE SESSION. - ISOLATION AND LONELINESS | INSTRUCTIONS_1","LOOKING BACK ON THE ENTIRETY OF YOUR SESSIONS, PLEASE RATE THE DEGREE TO WHICH AT ANY TIME DURING THAT SESSION YOU EXPERIENCED THE FOLLOWING PHENOMENA. ANSWER EACH QUESTION ACCORDING TO YOUR FEELINGS, THOUGHTS, AND EXPERIENCES AT THE TIME OF THE SESSION. - SADNESS | INSTRUCTIONS_2","LOOKING BACK ON THE ENTIRETY OF YOUR SESSIONS, PLEASE RATE THE DEGREE TO WHICH AT ANY TIME DURING THAT SESSION YOU EXPERIENCED THE FOLLOWING PHENOMENA. ANSWER EACH QUESTION ACCORDING TO YOUR FEELINGS, THOUGHTS, AND EXPERIENCES AT THE TIME OF THE SESSION. - FEELING MY HEART BEATING | INSTRUCTIONS_3","LOOKING BACK ON THE ENTIRETY OF YOUR SESSIONS, PLEASE RATE THE DEGREE TO WHICH AT ANY TIME DURING THAT SESSION YOU EXPERIENCED THE FOLLOWING PHENOMENA. ANSWER EACH QUESTION ACCORDING TO YOUR FEELINGS, THOUGHTS, AND EXPERIENCES AT THE TIME OF THE SESSION. - I HAD THE FEELING SOMETHING HORRIBLE WOULD HAPPEN | INSTRUCTIONS_4","LOOKING BACK ON THE ENTIRETY OF YOUR SESSIONS, PLEASE RATE THE DEGREE TO WHICH AT ANY TIME DURING THAT SESSION YOU EXPERIENCED THE FOLLOWING PHENOMENA. ANSWER EACH QUESTION ACCORDING TO YOUR FEELINGS, THOUGHTS, AND EXPERIENCES AT THE TIME OF THE SESSION. - FEELING MY BODY SHAKE/SCRAMBLE | INSTRUCTIONS_5","LOOKING BACK ON THE ENTIRETY OF YOUR SESSIONS, PLEASE RATE THE DEGREE TO WHICH AT ANY TIME DURING THAT SESSION YOU EXPERIENCED THE FOLLOWING PHENOMENA. ANSWER EACH QUESTION ACCORDING TO YOUR FEELINGS, THOUGHTS, AND EXPERIENCES AT THE TIME OF THE SESSION. - FEELINGS OF GRIEF | INSTRUCTIONS_6","LOOKING BACK ON THE ENTIRETY OF YOUR SESSIONS, PLEASE RATE THE DEGREE TO WHICH AT ANY TIME DURING THAT SESSION YOU EXPERIENCED THE FOLLOWING PHENOMENA. ANSWER EACH QUESTION ACCORDING TO YOUR FEELINGS, THOUGHTS, AND EXPERIENCES AT THE TIME OF THE SESSION. - EXPERIENCE OF FEAR | INSTRUCTIONS_7","LOOKING BACK ON THE ENTIRETY OF YOUR SESSIONS, PLEASE RATE THE DEGREE TO WHICH AT ANY TIME DURING THAT SESSION YOU EXPERIENCED THE FOLLOWING PHENOMENA. ANSWER EACH QUESTION ACCORDING TO YOUR FEELINGS, THOUGHTS, AND EXPERIENCES AT THE TIME OF THE SESSION. - FEAR THAT I MIGHT LOSE MY MIND OR GO INSANE | INSTRUCTIONS_8","LOOKING BACK ON THE ENTIRETY OF YOUR SESSIONS, PLEASE RATE THE DEGREE TO WHICH AT ANY TIME DURING THAT SESSION YOU EXPERIENCED THE FOLLOWING PHENOMENA. ANSWER EACH QUESTION ACCORDING TO YOUR FEELINGS, THOUGHTS, AND EXPERIENCES AT THE TIME OF THE SESSION. - I FELT LIKE CRYING | INSTRUCTIONS_9","LOOKING BACK ON THE ENTIRETY OF YOUR SESSIONS, PLEASE RATE THE DEGREE TO WHICH AT ANY TIME DURING THAT SESSION YOU EXPERIENCED THE FOLLOWING PHENOMENA. ANSWER EACH QUESTION ACCORDING TO YOUR FEELINGS, THOUGHTS, AND EXPERIENCES AT THE TIME OF THE SESSION. - FEELING OF ISOLATION FROM PEOPLE AND THINGS | INSTRUCTIONS_10","LOOKING BACK ON THE ENTIRETY OF YOUR SESSIONS, PLEASE RATE THE DEGREE TO WHICH AT ANY TIME DURING THAT SESSION YOU EXPERIENCED THE FOLLOWING PHENOMENA. ANSWER EACH QUESTION ACCORDING TO YOUR FEELINGS, THOUGHTS, AND EXPERIENCES AT THE TIME OF THE SESSION. - FEELINGS OF DESPAIR | INSTRUCTIONS_11","LOOKING BACK ON THE ENTIRETY OF YOUR SESSIONS, PLEASE RATE THE DEGREE TO WHICH AT ANY TIME DURING THAT SESSION YOU EXPERIENCED THE FOLLOWING PHENOMENA. ANSWER EACH QUESTION ACCORDING TO YOUR FEELINGS, THOUGHTS, AND EXPERIENCES AT THE TIME OF THE SESSION. - I HAD THE FEELING THAT PEOPLE WERE PLOTTING AGAINST ME | INSTRUCTIONS_12","LOOKING BACK ON THE ENTIRETY OF YOUR SESSIONS, PLEASE RATE THE DEGREE TO WHICH AT ANY TIME DURING THAT SESSION YOU EXPERIENCED THE FOLLOWING PHENOMENA. ANSWER EACH QUESTION ACCORDING TO YOUR FEELINGS, THOUGHTS, AND EXPERIENCES AT THE TIME OF THE SESSION. - I WAS AFRAID THAT THE STATE I WAS IN WOULD LAST FOREVER | INSTRUCTIONS_13","LOOKING BACK ON THE ENTIRETY OF YOUR SESSIONS, PLEASE RATE THE DEGREE TO WHICH AT ANY TIME DURING THAT SESSION YOU EXPERIENCED THE FOLLOWING PHENOMENA. ANSWER EACH QUESTION ACCORDING TO YOUR FEELINGS, THOUGHTS, AND EXPERIENCES AT THE TIME OF THE SESSION. - ANXIOUSNESS | INSTRUCTIONS_14","LOOKING BACK ON THE ENTIRETY OF YOUR SESSIONS, PLEASE RATE THE DEGREE TO WHICH AT ANY TIME DURING THAT SESSION YOU EXPERIENCED THE FOLLOWING PHENOMENA. ANSWER EACH QUESTION ACCORDING TO YOUR FEELINGS, THOUGHTS, AND EXPERIENCES AT THE TIME OF THE SESSION. - I FELT SHAKY INSIDE | INSTRUCTIONS_15","LOOKING BACK ON THE ENTIRETY OF YOUR SESSIONS, PLEASE RATE THE DEGREE TO WHICH AT ANY TIME DURING THAT SESSION YOU EXPERIENCED THE FOLLOWING PHENOMENA. ANSWER EACH QUESTION ACCORDING TO YOUR FEELINGS, THOUGHTS, AND EXPERIENCES AT THE TIME OF THE SESSION. - I HAD THE PROFOUND EXPERIENCE OF MY OWN DEATH | INSTRUCTIONS_16","LOOKING BACK ON THE ENTIRETY OF YOUR SESSIONS, PLEASE RATE THE DEGREE TO WHICH AT ANY TIME DURING THAT SESSION YOU EXPERIENCED THE FOLLOWING PHENOMENA. ANSWER EACH QUESTION ACCORDING TO YOUR FEELINGS, THOUGHT

In [2]:
import pandas as pd
import numpy as np

# ✅ Load dataset
df = long_df_merged.copy()

# ✅ Rename the dummy CEQ column to correct label
df.rename(columns={
    'LOOKING BACK ON THE ENTIRETY OF YOUR SESSIONS, PLEASE RATE THE DEGREE TO WHICH AT ANY TIME DURING THAT SESSION YOU EXPERIENCED THE FOLLOWING PHENOMENA. ANSWER EACH QUESTION ACCORDING TO YOUR FEELINGS, THOUGHTS, AND EXPERIENCES AT THE TIME OF THE SESSION. - CLICK TO WRITE STATEMENT 26 | INSTRUCTIONS_26':
    'LOOKING BACK... - I FELT FRIGHTENED | INSTRUCTIONS_26'
}, inplace=True)

# ✅ Label mapping
label_map = {
    'none at all': 0,
    'none; not at all': 0,
    'slight': 1,
    'so slight cannot decide': 1,
    'so slight, cannot detect': 1,
    'moderate': 2,
    'strong': 3,
    'strong (equivalent in degree to any other strong experience)': 3,
    'very strong': 4,
    'extreme': 5,
    'extreme (more than any other time in my life)': 5,
    'extreme (more than ever before in my life)': 5,
    'complete': 5,
    '': np.nan,
    'nan': np.nan,
    'NaN': np.nan
}

# ✅ Identify CEQ and MEQ columns
ceq_exact_phrases = [
    'isolation and loneliness', 'sadness', 'feeling my heart beating',
    'i had the feeling something horrible would happen', 'feeling my body shake',
    'feelings of grief', 'experience of fear', 'fear that i might lose my mind or go insane',
    'i felt like crying', 'feeling of isolation from people and things', 'feelings of despair',
    'i had the feeling that people were plotting against me', 'i was afraid that the state i was in would last forever',
    'anxiousness', 'i felt shaky inside', 'i had the profound experience of my own death',
    'i felt my heart beating irregularly or skipping beats', 'pressure or weight in my chest or abdomen',
    'i experienced a decreased sense of sanity', 'i felt as if i was dead or dying', 'panic',
    'experience of antagonism toward people around me', 'despair', 'i felt isolated from everything and everyone',
    'emotional and/or physical suffering', 'i felt frightened'
]

ceq_cols = [
    col for col in df.columns
    if 'looking back' in col.lower() and any(phrase in col.lower() for phrase in ceq_exact_phrases)
]

meq_cols = [
    col for col in df.columns
    if 'looking back' in col.lower() and col not in ceq_cols
]

print(f"✔️ CEQ columns: {len(ceq_cols)}")
print(f"✔️ MEQ columns: {len(meq_cols)}")

# ✅ Map responses to numbers
def map_responses(df, columns):
    for col in columns:
        df[col] = (
            df[col]
            .astype(str)
            .str.strip()
            .str.lower()
            .replace(label_map)
        )
    return df

df = map_responses(df, meq_cols + ceq_cols)

# ✅ Clean column names for publication
meq_rename_map = {
    col: 'MEQ30_' + col.split(' - ')[-1].split(' | ')[0].strip().replace(' ', '').replace('"', '').replace("'", "")
    for col in meq_cols
}

ceq_rename_map = {
    col: 'CEQ30_' + col.split(' - ')[-1].split(' | ')[0].strip().replace(' ', '').replace('"', '').replace("'", "")
    for col in ceq_cols
}

df = df.rename(columns={**meq_rename_map, **ceq_rename_map})

meq_cols_clean = list(meq_rename_map.values())
ceq_cols_clean = list(ceq_rename_map.values())

# ✅ MEQ Scoring
ineffability_items = [col for col in meq_cols_clean if 'describ' in col.lower() or 'difficulttocommunicate' in col.lower()]
mystical_items = [col for col in meq_cols_clean if any(kw in col.lower() for kw in [
    'oneness', 'ultimatereality', 'sacred', 'reverence', 'purebeing', 'spiritualheight',
    'unity', 'fusion', 'eternity', 'insight', 'presence', 'life', 'allisone'
])]
positive_items = [col for col in meq_cols_clean if any(kw in col.lower() for kw in [
    'amazement', 'tenderness', 'peace', 'ecstasy', 'awe', 'joy'
])]
transcendence_items = [col for col in meq_cols_clean if any(kw in col.lower() for kw in [
    'time', 'space', 'timelessness', 'realm', 'awarenessofwhereyouare'
])]

df['MEQ30_Ineffability'] = df[ineffability_items].astype(float).mean(axis=1)
df['MEQ30_MysticalExperience'] = df[mystical_items].astype(float).mean(axis=1)
df['MEQ30_PositiveMood'] = df[positive_items].astype(float).mean(axis=1)
df['MEQ30_TranscendenceOfTimeAndSpace'] = df[transcendence_items].astype(float).mean(axis=1)
df['MEQ30_TotalScore'] = df[meq_cols_clean].astype(float).mean(axis=1)

# ✅ CEQ Scoring
isolation_items = [col for col in ceq_cols_clean if 'isolation' in col.lower() or 'loneliness' in col.lower()]
fear_items = [col for col in ceq_cols_clean if 'fear' in col.lower() or 'panic' in col.lower() or 'frightened' in col.lower() or 'anxiousness' in col.lower()]
grief_items = [col for col in ceq_cols_clean if 'grief' in col.lower() or 'sadness' in col.lower() or 'crying' in col.lower() or 'despair' in col.lower()]
insanity_items = [col for col in ceq_cols_clean if 'insane' in col.lower() or 'sanity' in col.lower() or 'mind' in col.lower()]
death_items = [col for col in ceq_cols_clean if 'death' in col.lower() or 'dying' in col.lower()]
paranoia_items = [col for col in ceq_cols_clean if 'paranoia' in col.lower() or 'plott' in col.lower()]
physical_items = [col for col in ceq_cols_clean if any(kw in col.lower() for kw in [
    'body', 'physical', 'heartbeating', 'shaky', 'pressure', 'suffering', 'pain'
])]

# Helper function to score a subscale using the 30% missing rule
def score_subscale(df, item_list, subscale_name, min_prop_complete=0.7):
    item_array = df[item_list].astype(float)
    n_items = len(item_list)
    valid_count = item_array.notna().sum(axis=1)
    score = item_array.mean(axis=1)
    score = score.where(valid_count >= n_items * min_prop_complete)
    df[subscale_name] = score
    return df

# ✅ Score MEQ30 subscales
df = score_subscale(df, ineffability_items, 'MEQ30_Ineffability', min_prop_complete=0.7)
df = score_subscale(df, mystical_items, 'MEQ30_MysticalExperience', min_prop_complete=0.7)
df = score_subscale(df, positive_items, 'MEQ30_PositiveMood', min_prop_complete=0.7)
df = score_subscale(df, transcendence_items, 'MEQ30_TranscendenceOfTimeAndSpace', min_prop_complete=0.7)

# ✅ Compute MEQ30 Total only if all 4 subscales are present
df['MEQ30_TotalScore'] = df[[
    'MEQ30_Ineffability',
    'MEQ30_MysticalExperience',
    'MEQ30_PositiveMood',
    'MEQ30_TranscendenceOfTimeAndSpace'
]].mean(axis=1).where(df[[
    'MEQ30_Ineffability',
    'MEQ30_MysticalExperience',
    'MEQ30_PositiveMood',
    'MEQ30_TranscendenceOfTimeAndSpace'
]].notna().all(axis=1))

# ✅ Score CEQ30 subscales
df = score_subscale(df, isolation_items, 'CEQ30_Isolation_SUM', min_prop_complete=0.7)
df = score_subscale(df, fear_items, 'CEQ30_Fear_SUM', min_prop_complete=0.7)
df = score_subscale(df, grief_items, 'CEQ30_Grief_SUM', min_prop_complete=0.7)
df = score_subscale(df, insanity_items, 'CEQ30_Insanity_SUM', min_prop_complete=0.7)
df = score_subscale(df, death_items, 'CEQ30_Death_SUM', min_prop_complete=0.7)
df = score_subscale(df, paranoia_items, 'CEQ30_Paranoia_SUM', min_prop_complete=0.7)
df = score_subscale(df, physical_items, 'CEQ30_PhysicalDistress_SUM', min_prop_complete=0.7)

# ✅ Compute CEQ30 Total only if all 7 subscales are present
df['CEQ30_Total_SUM'] = df[[
    'CEQ30_Isolation_SUM', 'CEQ30_Fear_SUM', 'CEQ30_Grief_SUM',
    'CEQ30_Insanity_SUM', 'CEQ30_Death_SUM', 'CEQ30_Paranoia_SUM',
    'CEQ30_PhysicalDistress_SUM'
]].mean(axis=1).where(df[[
    'CEQ30_Isolation_SUM', 'CEQ30_Fear_SUM', 'CEQ30_Grief_SUM',
    'CEQ30_Insanity_SUM', 'CEQ30_Death_SUM', 'CEQ30_Paranoia_SUM',
    'CEQ30_PhysicalDistress_SUM'
]].notna().all(axis=1))

# ✅ Drop item-level columns after scoring
df.drop(columns=meq_cols_clean + ceq_cols_clean, inplace=True)

# ✅ Save or return updated DataFrame
df.to_csv("Kambo_df_with_MEQ_and_CEQ_scored_thresholded.csv", index=False)

✔️ CEQ columns: 26
✔️ MEQ columns: 30

/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)
/tmp/ipython-input-2-3968774417.py:68: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  .replace(label_map)

In [3]:
pd.Series(df.columns.tolist()).to_csv('Column_List.csv', index=False)

In [4]:
import pandas as pd
import numpy as np

### 📥 Load Data
df_columns = pd.read_csv('/content/drive/MyDrive/Kambo/ColumnNames.csv')

### 🧼 Clean & Prepare Column Names

def safe_str(x):
    return str(x) if pd.notna(x) else ''

def clean_column(col):
    col = safe_str(col)
    return (
        col.lower()
        .split('|')[0]
        .replace('click to write the question text - ', '')
        .replace('with respect to your previous kambo session, please drag the slider to indicate how much you agree with the following statements. - ', '')
        .strip()
        .replace('.', '')
        .replace(' ', '_')
    )

# Extract mappings from the columns file
columns_100_point = list(df_columns.columns)
columns_5_point = list(df_columns.iloc[0])

hundred_cols = [col for col in columns_100_point if pd.notna(col)]
five_cols = [col for col in columns_5_point if pd.notna(col)]

# Create rename maps
hundred_map = {col: clean_column(col) + '_100scale' for col in hundred_cols if col in df.columns}
five_map = {col: clean_column(col) + '_5scale' for col in five_cols if col in df.columns}

### 🔁 Clean Values for 5-point Columns

def clean_5scale_value(x):
    x = str(x).strip().lower()
    replacements = {
        'yes, much more than usualy': 'yes, much more than usually',
        'yes, much more than usually': 100,
        'no, not more than usually': 0,
        '1': 0, '2': 25, '3': 50, '4': 75, '5': 100,
    }
    return replacements.get(x, np.nan)

for col in five_cols:
    if col in df.columns:
        df[col] = df[col].apply(clean_5scale_value)

### 🏷️ Rename Columns
df = df.rename(columns={**hundred_map, **five_map})

# Drop duplicate columns
df = df.loc[:, ~df.columns.duplicated()]

### 🔀 Combine 5-point and 100-point into unified items
dasc_items = list(set(
    [v.replace('_100scale', '') for v in hundred_map.values()] +
    [v.replace('_5scale', '') for v in five_map.values()]
))

for item in dasc_items:
    col_100 = item + '_100scale'
    col_5 = item + '_5scale'
    if col_100 in df.columns and col_5 in df.columns:
        df[item] = df[col_100].combine_first(df[col_5])
    elif col_100 in df.columns:
        df[item] = df[col_100]
    elif col_5 in df.columns:
        df[item] = df[col_5]

df[dasc_items] = df[dasc_items].apply(pd.to_numeric, errors='coerce')

### 🧠 Define 5DASC Subscales
subscales = {
    "5DASC_OceanicBoundlessness": [
        "i_experienced_a_touch_of_eternity",
        "everything_seemed_to_unify_into_a_oneness",
        "conflicts_and_contradictions_seemed_to_dissolve",
        "i_felt_one_with_my_surroundings",
        "i_experienced_an_all-embracing_love",
        "worries_and_anxieties_of_everyday_life_felt_unimportant",
        "i_felt_extraordinary_powers_within_myself",
        "my_experience_had_religious_aspects_to_it",
        "i_felt_totally_free_and_released_from_all_obligations",
        "i_experienced_profound_inner_peace"
    ],
    "5DASC_AnxiousEgoDissolution": [
        "i_felt_tormented",
        "i_felt_threatened",
        "i_felt_as_if_dark_forces_had_overtaken_me",
        "i_was_afraid_that_the_state_i_was_in_would_last_forever",
        "i_was_scared_without_knowing_exactly_why",
        "i_felt_as_if_i_were_paralyzed",
        "i_felt_that_i_was_on_the_verge_of_unconsciousness",
        "i_felt_like_a_puppet_or_marionette"
    ],
    "5DASC_VisionaryRestructuralization": [
        "i_saw_regular_patterns_with_closed_eyes_or_in_complete_darkness",
        "i_saw_colors_with_closed_eyes_or_in_complete_darkness",
        "i_saw_brightness_or_flashes_of_light_with_closed_eyes_or_in_complete_darkness",
        "i_could_see_images_from_my_memory_or_imagination_with_extreme_clarity",
        "everything_around_me_seemed_to_be_animated_with_life",
        "objects_in_my_surroundings_engaged_me_emotionally_much_more_than_usual"
    ],
    "5DASC_AuditoryAlterations": [
        "i_heard_single_words_without_knowing_where_they_came_from",
        "i_heard_complete_sentences_without_knowing_where_they_came_from",
        "i_heard_my_thoughts_as_if_i_had_spoken_them_out_loud",
        "i_heard_music_without_knowing_where_it_came_from",
        "i_heard_voices_that_did_not_come_from_the_surroundings_as_usual",
        "i_heard_something_like_a_buzzing,_swooshing,_or_humming_without_recognizing_the_cause"
    ],
    "5DASC_ReductionOfVigilance": [
        "i_felt_sleepy",
        "i_felt_drowsy",
        "i_felt_like_i_do_shortly_before_falling_asleep",
        "i_felt_i_was_about_to_fall_asleep",
        "i_felt_drunk",
        "i_felt_as_if_i_was_half-asleep",
        "my_thoughts_and_actions_were_slowed_down",
        "i_felt_exhausted"
    ]
}

### 🧮 Score Each Subscale with 70% Rule
def score_subscale(df, items, subscale_name, min_prop_complete=0.7):
    matched_items = [item for item in items if item in df.columns]
    n_items = len(matched_items)
    item_data = df[matched_items].astype(float)
    valid_counts = item_data.notna().sum(axis=1)
    score = item_data.mean(axis=1)
    score = score.where(valid_counts >= n_items * min_prop_complete)
    df[f'{subscale_name}_Score'] = score
    return df

for subscale_name, items in subscales.items():
    df = score_subscale(df, items, subscale_name, min_prop_complete=0.7)

subscale_score_cols = [f'{s}_Score' for s in subscales.keys()]
df["5DASC_TotalScore"] = df[subscale_score_cols].mean(axis=1).where(df[subscale_score_cols].notna().all(axis=1))

### 💾 Save Output
df_clean = df.drop(columns=[c for c in df.columns if c.endswith('_100scale') or c.endswith('_5scale') or c in dasc_items], errors='ignore')
df_clean.to_csv("Kambo_with_5DASC_scored_clean.csv", index=False)

/tmp/ipython-input-4-3862821393.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = df[col_5]
/tmp/ipython-input-4-3862821393.py:67: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = df[col_100].combine_first(df[col_5])
/tmp/ipython-input-4-3862821393.py:71: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[item] = df[col_5]
/tmp/ipython-input-4-3862821393.py:135: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'{subscale_name}_Score'] = score
/tmp/ipython-input-4-3862821393.py:135: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'{subscale_name}_Score'] = score
/tmp/ipython-input-4-3862821393.py:135: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'{subscale_name}_Score'] = score
/tmp/ipython-input-4-3862821393.py:135: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'{subscale_name}_Score'] = score
/tmp/ipython-input-4-3862821393.py:135: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'{subscale_name}_Score'] = score
/tmp/ipython-input-4-3862821393.py:142: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["5DASC_TotalScore"] = df[subscale_score_cols].mean(axis=1).where(df[subscale_score_cols].notna().all(axis=1))

In [5]:
# Step 1: Clean MAAS column names
def clean_maas_column(col):
    return col.split('|')[-1].strip().lower()

# Identify and map MAAS columns
maas_cols_raw = [col for col in df_clean.columns if 'MAAS_' in col]
maas_cols_clean = [clean_maas_column(c) for c in maas_cols_raw]
maas_col_map = dict(zip(maas_cols_clean, maas_cols_raw))

# Step 2: Define the text-to-score mapping
maas_map = {
    'almost never': 1,
    'very infrequently': 2,
    'somewhat infrequently': 3,
    'somewhat frequently': 4,
    'very frequently': 5,
    'almost always': 6
}

# Step 3: Apply mapping to each MAAS column
for col in maas_cols_raw:
    df_clean[col] = df_clean[col].astype(str).str.strip().str.lower().map(maas_map)

# Step 4: Compute MAAS Total Score (30% missing rule = at least 11 of 15 valid)
def score_maas_total(df_clean, maas_cols_raw, output_col='MAAS_Total', min_valid=11):
    item_data = df_clean[maas_cols_raw].astype(float)
    valid_counts = item_data.notna().sum(axis=1)
    mean_score = item_data.mean(axis=1)
    df_clean[output_col] = mean_score.where(valid_counts >= min_valid)
    return df_clean

# Step 5: Score and export
df_maas = score_maas_total(df_clean, maas_cols_raw, output_col='MAAS_Total')
df_maas_clean = df_maas.drop(columns=maas_cols_raw, errors='ignore')
df_maas_clean.to_csv("Kambo_with_MAAS_scored.csv", index=False)

In [6]:
df = df_maas_clean.copy()

# Step 1: Define response mapping and reverse-score item numbers
ryff_map = {
    'strongly disagree': 1,
    'somewhat disagree': 2,
    'a little disagree': 3,
    'neither agree nor disagree': 4,
    'a little agree': 5,
    'somewhat agree': 6,
    'strongly agree': 7
}

reverse_items = [
    5, 8, 9, 10, 11, 12, 14, 15, 16,
    18, 19, 20, 23, 24, 25, 26, 29, 32, 33
]

# Step 2: Identify Ryff columns and create reverse-score list
ryff_cols_raw = [col for col in df.columns if '| RYFF_' in col]
reverse_cols = [col for col in ryff_cols_raw if any(col.strip().endswith(f'RYFF_{i}') for i in reverse_items)]

# Step 3: Clean and map all Ryff columns to numeric values
for col in ryff_cols_raw:
    df[col] = df[col].astype(str).str.strip().str.lower().map(ryff_map)

# Step 4: Reverse-score appropriate items
for col in reverse_cols:
    df[col] = df[col].apply(lambda x: 8 - x if pd.notnull(x) else np.nan)

# Step 5: Score total Ryff using 30% missing rule (≥ 30 of 42 answered)
def score_ryff_total(df, cols, output_col='RYFF_Total', min_valid=30):
    data = df[cols].astype(float)
    valid_counts = data.notna().sum(axis=1)
    mean_score = data.mean(axis=1)
    df[output_col] = mean_score.where(valid_counts >= min_valid)
    return df

df = score_ryff_total(df, ryff_cols_raw, output_col='RYFF_Total')

# Step 6: Subscale definitions
ryff_subscales = {
    "Autonomy": [1, 7, 13, 19, 25, 31, 37],
    "EnvironmentalMastery": [2, 8, 14, 20, 26, 32, 38],
    "PersonalGrowth": [3, 9, 15, 21, 27, 33, 39],
    "PositiveRelations": [4, 10, 16, 22, 28, 34, 40],
    "PurposeInLife": [5, 11, 17, 23, 29, 35, 41],
    "SelfAcceptance": [6, 12, 18, 24, 30, 36, 42],
}

# Step 7: Create item map (e.g., 'RYFF_1' → actual column name)
ryff_col_map = {
    f"RYFF_{i}": col for i in range(1, 43)
    for col in df.columns if col.strip().endswith(f'RYFF_{i}')
}

# Step 8: Subscale scoring with 30% missing rule
def score_subscale(df, col_map, item_nums, name, min_valid_ratio=0.7):
    cols = [col_map[f"RYFF_{i}"] for i in item_nums if f"RYFF_{i}" in col_map]
    valid_counts = df[cols].notna().sum(axis=1)
    score = df[cols].mean(axis=1)
    score = score.where(valid_counts >= len(cols) * min_valid_ratio)
    df[f"RYFF_{name}_Score"] = score
    return df

for name, item_nums in ryff_subscales.items():
    df = score_subscale(df, ryff_col_map, item_nums, name)

# Final Step: Drop item-level columns and export
df_ryff = df.drop(columns=ryff_cols_raw, errors='ignore')
df_ryff.to_csv("Kambo_with_Ryff_scored.csv", index=False)

In [7]:
df_ryff.head()

,Unnamed: 0,START DATE | STARTDATE,END DATE | ENDDATE,RESPONSE TYPE | STATUS,IP ADDRESS | IPADDRESS,PROGRESS,DURATION (IN SECONDS),FINISHED,RECORDED DATE | RECORDEDDATE,RESPONSE ID | RESPONSEID,RECIPIENT LAST NAME | RECIPIENTLASTNAME,RECIPIENT FIRST NAME | RECIPIENTFIRSTNAME,RECIPIENT EMAIL | RECIPIENTEMAIL,EXTERNAL DATA REFERENCE | EXTERNALREFERENCE,LOCATION LATITUDE | LOCATIONLATITUDE,LOCATION LONGITUDE | LOCATIONLONGITUDE,DISTRIBUTION CHANNEL | DISTRIBUTIONCHANNEL,USER LANGUAGE | USERLANGUAGE,WHAT IS THE NAME OF THE PRACTITIONER YOU WILL BE WORKING WITH? | GEN.1.,WHAT IS THE DATE OF YOUR 1ST SCHEDULED KAMBO SESSION? | GEN.2.,WHAT IS THE DATE OF YOUR 3RD SCHEDULED KAMBO SESSION? | GEN.3.,WHAT IS YOUR AGE? | DEMO.1.,WHAT BIOLOGICAL SEX WERE YOU ASSIGNED AT BIRTH? | DEMO.2.,WHAT GENDER DO YOU IDENTIFY WITH? - SELECTED CHOICE | DEMO.3.,WHAT GENDER DO YOU IDENTIFY WITH? - OTHER - TEXT | DEMO.3._7_TEXT,WHAT RACE DO YOU IDENTIFY AS? | DEMO.4.,WHAT IS YOUR HIGHEST LEVEL OF EDUCATION COMPLETED? | DEMO.5.,WHAT IS YOUR GROSS HOUSEHOLD INCOME? | DEMO.6.,"WHAT IS YOUR APPROXIMATE HEIGHT (FT, IN)? | DEMO.7.",WHAT IS YOUR APPROXIMATE WEIGHT (LBS)? | DEMO.8.,HAVE YOU BEEN DIAGNOSED WITH ANY MEDICAL CONDITIONS OR DISEASE? DO YOU CURRENTLY DEAL WITH THESE CONDITIONS OR HAVE YOU RECOVERED FROM THESE CONDITIONS? PLEASE EXPLAIN. | DEMO.9.,HAVE YOU BEEN DIAGNOSED WITH LYME DISEASE BY A LICENSED HEALTHCARE PROFESSIONAL? | DEMO.10.,HAVE YOU BEEN DIAGNOSED WITH POST-TREATMENT LYME SYNDROME BY A LICENSED HEALTHCARE PROFESSIONAL? | DEMO.11.,"PLEASE LIST ANY DRUGS, MEDICATIONS, OR SUPPLEMENTS YOU ARE CURRENTLY TAKING. | DEMO.12.","HAVE YOU EVER USED A PSYCHEDELIC SUBSTANCE SUCH AS LSD, PSILOCYBIN (MAGIC) MUSHROOMS, MESCALINE (PEYOTE), DMT, OR AYAHUASCA? | DEMO.13.",DO YOU USE CANNABIS? | DEMO.14.,WHAT ARE THE REASONS YOU HAVE SOUGHT OUT KAMBO? | DEMO.15.,PLEASE SELECT THE OPTION THAT REFLECTS HOW NERVOUS YOU ARE FEELING ABOUT YOUR UPCOMING KAMBO EXPERIENCES. | DEMO.16.,PLEASE SELECT THE OPTION THAT REFLECTS HOW EXCITED YOU ARE FEELING ABOUT YOUR UPCOMING KAMBO EXPERIENCES. | DEMO.17.,CLICK TO WRITE THE QUESTION TEXT - I FEEL FIT | MFI_1,"CLICK TO WRITE THE QUESTION TEXT - PHYSICALLY, I FEEL ONLY ABLE TO DO A LITTLE | MFI_2",CLICK TO WRITE THE QUESTION TEXT - I FEEL VERY ACTIVE | MFI_3,CLICK TO WRITE THE QUESTION TEXT - I FEEL LIKE DOING ALL SORTS OF NICE THINGS | MFI_4,CLICK TO WRITE THE QUESTION TEXT - I FEEL TIRED | MFI_5,CLICK TO WRITE THE QUESTION TEXT - I THINK I DO A LOT IN A DAY | MFI_6,"CLICK TO WRITE THE QUESTION TEXT - WHEN I AM DOING SOMETHING, I CAN KEEP MY THOUGHTS ON IT | MFI_7",CLICK TO WRITE THE QUESTION TEXT - PHYSICALLY I CAN TAKE ON A LOT | MFI_8,CLICK TO WRITE THE QUESTION TEXT - I DREAD HAVING TO DO THINGS | MFI_9,CLICK TO WRITE THE QUESTION TEXT - I THINK I DO VERY LITTLE IN A DAY | MFI_10,CLICK TO WRITE THE QUESTION TEXT - I CAN CONCENTRATE WELL | MFI_11,CLICK TO WRITE THE QUESTION TEXT - I AM RESTED | MFI_12,CLICK TO WRITE THE QUESTION TEXT - IT TAKES A LOT OF EFFORT TO CONCENTRATE ON THINGS | MFI_13,CLICK TO WRITE THE QUESTION TEXT - PHYSICALLY I FEEL I AM IN A BAD CONDITION | MFI_14,CLICK TO WRITE THE QUESTION TEXT - I HAVE A LOT OF PLANS | MFI_15,CLICK TO WRITE THE QUESTION TEXT - I TIRE EASILY | MFI_16,CLICK TO WRITE THE QUESTION TEXT - I GET LITTLE DONE | MFI_17,CLICK TO WRITE THE QUESTION TEXT - I DON'T FEEL LIKE DOING ANYTHING | MFI_18,CLICK TO WRITE THE QUESTION TEXT - MY THOUGHTS EASILY WANDER | MFI_19,CLICK TO WRITE THE QUESTION TEXT - PHYSICALLY I FEEL I AM IN AN EXCELLENT CONDITION | MFI_20,FALLING ASLEEP: | IDS.1.,SLEEP DURING THE NIGHT: | IDS.2.,WAKING UP TOO EARLY: | IDS.3.,SLEEPING TOO MUCH: | IDS.4.,FEELING SAD: | IDS.5.,FEELING IRRITABLE: | IDS.6.,FEELING ANXIOUS OR TENSE: | IDS.7.,RESPONSE OF YOUR MOOD TO GOOD OR DESIRED EVENTS: | IDS.8.,MOOD IN RELATION TO THE TIME OF DAY: | IDS.9.,MY MOOD IS TYPICALLY WORSE IN THE... | IDS.9A.,IS YOUR MOOD VARIATION ATTRIBUTED TO ENVIRONMENT? | IDS.9B.,THE QUALITY OF YOUR MOOD: | IDS.10.,DECREASED APPETITE: | IDS.11.,INCREASED APPETITE: | IDS.12.,DECREASED WEIGHT (WITHIN THE LAST TWO WEEKS): | IDS.13.,INCREASED WEIGHT (WITHIN THE LAST TWO WEEKS): | IDS.14.,CONCENTRATION/DECISION MAKING: | IDS.15.,VIEW OF MYSELF: | IDS.16.,VIEW OF MY FUTURE | IDS.17.,THOUGHTS OF DEATH OR SUICIDE: | IDS.18.,GENERAL INTEREST: | IDS.19.,ENERGY LEVELS: | IDS.20.,CAPACITY FOR PLEASURE OR ENJOYMENT (EXCLUDING SEX): | IDS.21.,"INTEREST IN SEX (PLEASE RATE INTEREST, NOT ACTIVITY): | IDS.22.",FEELING SLOWED DOWN: | IDS.23.,FEELING RESTLESS: | IDS.24.,ACHES AND PAINS: | IDS.25.,OTHER BODILY SYMPTOMS: | IDS.26.,PANIC/PHOBIC SYMPTOMS: | IDS.27.,CONSTIPATION/DIARRHEA: | IDS.28.,INTERPERSONAL SENSITIVITY: | IDS.29.,LEADEN PARALYSIS/PHYSICAL ENERGY: | IDS.30.,"IN GENERAL, I CONSIDER MYSELF: | SHS.1","COMPARED WITH MOST OF MY PEERS, I CONSIDER MYSELF: | SHS.2","SOME PEOPLE ARE GENERALLY VERY HAPPY. THEY ENJOY LIFE REGARDLESS OF WHAT IS GOING ON, \r\nGETTING THE MOST OUT OF EVERYTHING. TO WHAT EXTENT DOES THIS CHARACTERIZATION DESCRIBE YOU? | SHS.3","SOME PEOPLE ARE GENERALLY NOT VERY HAPPY. ALTHOUGH THEY ARE NOT DEPRESSED, THEY NEVER \r\nSEEM AS HAPPY AS THEY MIGHT BE. TO WHAT EXTENT DOES THIS CHARACTERIZATION DESCRIBE YOU? | SHS.4","THROUGHOUT OUR LIVES, MOST OF US HAVE HAD PAIN FROM TIME TO TIME\n(SUCH AS MINOR HEADACHES, SPRAINS, AND TOOTHACHES). HAVE YOU HAD\nPAIN OTHER THAN THESE EVERYDAY KINDS OF PAIN DURING THE LAST WEEK? - SELECTED CHOICE | BPI.1.","THROUGHOUT OUR LIVES, MOST OF US HAVE HAD PAIN FROM TIME TO TIME\n(SUCH AS MINOR HEADACHES, SPRAINS, AND TOOTHACHES). HAVE YOU HAD\nPAIN OTHER THAN THESE EVERYDAY KINDS OF PAIN DURING THE LAST WEEK? - YES (PLEASE SPECIFY) - TEXT | BPI.1._1_TEXT",DID YOU TAKE PAIN MEDICATIONS IN THE LAST 7 DAYS? | BPI.1A.,I FEEL I HAVE HAD SOME PAIN THAT REQUIRES MEDICATION EACH AND EVERY DAY | BPI.1B.,PLEASE RATE YOUR PAIN ACCORDING TO THE FOLLOWING STATEMENTS: - PLEASE RATE YOUR PAIN BY FILLING IN THE ONE NUMBER THAT BEST DESCRIBES YOUR PAIN AT ITS WORST IN THE PAST 24 HOURS. | BPI.3._1,PLEASE RATE YOUR PAIN ACCORDING TO THE FOLLOWING STATEMENTS: - PLEASE RATE YOUR PAIN BY FILLING IN THE ONE NUMBER THAT BEST DESCRIBES YOUR PAIN AT ITS LEAST IN THE PAST 24 HOURS | BPI.3._2,PLEASE RATE YOUR PAIN ACCORDING TO THE FOLLOWING STATEMENTS: - PLEASE RATE YOUR PAIN BY FILLING IN THE ONE NUMBER THAT BEST DESCRIBES YOUR PAIN ON THE AVERAGE. | BPI.3._3,WHAT TREATMENTS OR MEDICATIONS ARE YOU RECEIVING FOR YOUR PAIN? | BPI.4.,"IN THE PAST 24 HOURS, HOW MUCH RELIEF HAVE PAIN TREATMENTS OR \nMEDICATIONS PROVIDED? PLEASE SELECT THE ONE PERCENTAGE THAT MOST\nSHOWS HOW MUCH RELIEF YOU HAVE RECEIVED. | BPI.5.","SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - GENERAL ACTIVITY | BPI.6._1","SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - MOOD | BPI.6._2","SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - WALKING ABILITY | BPI.6._3","SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - NORMAL WORK (INCLUDES BOTH WORK OUTSIDE THE HOME AND HOUSEWORK) | BPI.6._4","SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - RELATION WITH OTHER PEOPLE | BPI.6._5","SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - SLEEP | BPI.6._6","SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - ENJOYMENT OF LIFE | BPI.6._7",Phase,1.\tPLEASE BRIEFLY DESCRIBE YOUR EXPERIENCE IN THE KAMBO RITUAL: | QUAL.1.,2. WERE THERE SPECIFIC ASPECTS OF THE RITUAL THAT WERE PARTICULARLY VALUABLE? | QUAL.2.,3.\tWERE THERE SPECIFIC ASPECTS OF THE RITUAL THAT WERE PARTICULARLY CHALLENGING? | QUAL.3.,DID YOU EXPERIENCE ANY EMOTIONAL ELEMENTS OF THE KAMBO RITUAL? | QUAL.4.,5.\tDID YOU EXPERIENCE ANY SPIRITUAL ELEMENTS OF THE KAMBO RITUAL? | QUAL.5.,6.\tWHAT WERE THE REASONS YOU SOUGHT OUT KAMBO AND DID THE PROCESS SATISFY THEM? | QUAL 6.,"ON THE FOLLOWING PAGES YOU WILL FIND A NUMBER OF STATEMENTS AND BELOW EACH \nSTATEMENT A LINE WITH THE ENDPOINTS “NO, NOT MORE THAN USUALLY” AND “YES, MUCH MORE \nTHAN USUALLY.” THE LINE REPRESENTS SOMETHING LIKE A THERMOMETER THAT WILL BE USED TO \nASSESS ALTERATIONS FROM YOUR NORMAL WAKING CONSCIOUSNESS.\n\n\nPLEASE RATE TO WHAT EXTENT THE STATEMENTS APPLY TO YOUR PARTICULAR EXPERIENCE –\nCOMPARED TO NORMAL WAKING CONSCIOUSNESS – BY USING THE SLIDER ON THE LINE \nNEXT TO THE STATEMENTS.\n\n\nPLEASE NOTE THAT YOUR NORMAL WAKING CONSCIOUSNESS CORRESPONDS TO A MARK AT THE \nVERY LEFT END OF THE SCALE, I.E.: “NO, NOT MORE THAN USUALLY.” | INSTRUCTIONS","1.\tHAVE ANY OF THE PHYSICAL, EMOTIONAL OR SPIRITUAL EFFECTS FROM THE KAMBO PROCESS PERSISTED UNTIL THIS POINT? | QUAL.1.",3.\tDO YOU FEEL THAT THERE ARE ANY LASTING CHANGES FROM HAVING DONE KAMBO? | QUAL.3.,4. DID KAMBO HAVE ANY IMPACT ON YOUR LIFE? PLEASE DESCRIBE. | QUAL.4.,5.\tDO YOU HAVE THE INTENTION TO DO KAMBO AGAIN AT SOME POINT IN YOUR LIFE? WHY OR WHY NOT? | QUAL.5.,6.\tIS THERE ANYTHING ELSE YOU'D LIKE TO SHARE WITH US? | QUAL 6.,non_null_count,practitioner,scheduled session 1,scheduled session 3,Days btwn,Health diagnosis,Autoimmu,Meds,Session 1,# of points,location of points,Private or group,vomit,BM,Fainting,Rapeh,Sananga,Session 2,# of points.1,location of points.1,Private or group.1,vomit.1,BM.1,Fainting.1,Rapeh.1,Sananga.1,Session 3,# of points.2,location of points.2,Private or group.2,vomit.2,BM.2,Fainting.2,Rapeh.2,Sananga.2,Private_or_group_numeric,AnonID,MEQ30_Ineffability,MEQ30_MysticalExperience,MEQ30_PositiveMood,MEQ30_TranscendenceOfTimeAndSpace,MEQ30_TotalScore,CEQ30_Isolation_SUM,CEQ30_Fear_SUM,CEQ30_Grief_SUM,CEQ30_Insanity_SUM,CEQ30_Death_SUM,CEQ30_Paranoia_SUM,CEQ30_PhysicalDistress_SUM,CEQ30_Total_SUM,5DASC_OceanicBoundlessness_Score,5DASC_AnxiousEgoDissolution_Score,5DASC_VisionaryRestructuralization_Score,5DASC_AuditoryAlterations_Score,5DASC_ReductionOfVigilance_Score,5DASC_TotalScore,MAAS_Total,RYFF_Total,RYFF_Autonomy_Score,RYFF_EnvironmentalMastery_Score,RYFF_PersonalGrowth_Score,RYFF_PositiveRelations_Score,RYFF_PurposeInLife_Score,RYFF_SelfAcceptance_Score
0,0,2023-02-16 20:16:10,2023-02-16 21:05:37,IP Address,76.181.171.194,100,2966,True,2023-02-16 21:05:38,R_stm7DF0q0ZkFcoF,NaN,NaN,NaN,NaN,41.2463,-81.8310,anonymous,EN,Kevin Sheard,2/17/23,3/17/23,28.0,Female,Cis-Female,NaN,Other,"University (e.g., bachelor’s degree)","$25,000-$50,000 annually",5’3”,119,Multiple Sclerosis. Mostly recovered. Only dea...,No,No,Vit D/ fish oil/ brown seaweed,Yes,Often,I heard it could be beneficial for those with ...,6,Extremely excited,3,4,3,"1 - yes, that is true",2,"1 - yes, that is true",3,"1 - yes, that is true",3,5 - no that is not true,3,4,2,5 - no that is not true,"1 - yes, that is true",2,5 - no that is not true,4,2,3,"I take more than 60 minutes to fall asleep, mo...","I wake up at least once a night, but I go back...","Most of the time, I awaken no more than 30 min...","I sleep no longer than 7-8 hours/night, withou...",I feel sad less than half the time,I feel irritable more than half the time,I feel anxious (tense) more than half the time,My mood brightens to a normal level which last...,There is no regular relationship between my mo...,Night,No,The mood (internal feelings) that I experience...,NaN,I feel a need to eat more frequently than usual,NaN,I feel as if I've had a slight weight gain,I occasionally feel indecisive or find that my...,I see myself as equally worthwhile and deservi...,I have an optimistic view of my future,I do not think of suicide or death,There is no change from usual in how intereste...,I get tired more easily than usual,I enjoy pleasurable activities just as much as...,I'm just as interested in sex as usual,"I think, speak, and move at my usual rate of s...",I have impulses to move about and am quite res...,Sometimes I get headaches or pains in my stoma...,I have some of these symptoms but they are mil...,I have no spells of panic or specific fears (p...,There is no change in my usual bowel habits,"I have not felt easily rejected, slighted, cri...",I have occasionally experienced periods of fee...,6,4,4,4,Yes (please specify),Intermittent back pain,No,No,4,0 - No Pain,3,Red light therapy/ icy hot,90%,0 - Does not interfere,3,0 - Does not interfere,4,2,0 - Does not interfere,0 - Does not interfere,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,162,Kevin sheard,2/17,3/17,28.0,Multiple Sclerosis,x,NaN,NaN,3.0,upper arm,private,1,0.0,N,Y,Y,NaN,3.0,chest,private,Y,N,N,Y,Y,NaN,3,2 chest 1 neck,private,Y,N,N,Y,Y,0,P001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.400000,4.976190,5.428571,4.857143,5.857143,4.571429,4.000000,5.142857
1,1,3/22/2023 10:03,3/22/2023 11:26,IP Address,76.188.214.194,100,4965,True,3/22/2023 11:26,R_3CCuL24AWuFvoqH,NaN,NaN,NaN,NaN,41.4481,-82.0177,anonymous,EN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,5 - no that is not true,3,"1 - yes, that is true",2,"1 - yes, that is true",3,"1 - yes, that is true",4,5 - no that is not true,3,4,3,5 - no that is not true,"1 - yes, that is true",3,5 - no that is not true,5 - no that is not true,2,3,"I take at least 30 minutes to fall asleep, mor...","I wake up at least once a night, but I go back...","Most of the time, I awaken no more than 30 min...","I sleep no longer than 7-8 hours/night, withou...",I feel sad less than half the time,I feel irritable less than half the time,I feel anxious (tense) less than half the time,My mood brightens to a normal level which last...,My mood often relates to the time of day becau...,Night,Yes,The mood (internal feelings) that I experience...,NaN,I feel a need to eat more frequently than usual,NaN,I have gained 2 pounds or more,There is no change in my usual capacity to con...,I see myself as equally worthwhile and deservi...,I have an optimistic view of my future,I do not think of suicide or death,There is no change from usual in how intereste...,There is no change in my usual level of energy,I enjoy pleasurable activities just as much as...,I'm just as interested in sex as usual,"I think, speak, and move at my usual rate of s...",I do not feel restless,I don't have any feeling of heaviness in my ar...,I have some of these symptoms but they are mil...,I have no spells of panic or specific fears (p...,There is no change in my usual bowel habits,"I have not felt easily rejected, slighted, cri...",I have not experienced the physical sensation ...,6,4,5,3,No,NaN,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,My experience in the ritual was more miles tha...,The music Kevin played alleviated anxiety and ...,The sananga and hapé were more challenging tha...,"Yes, the second session started emotionally be...","Yes! After doing Kambò I started, noticing my ...",I have always had an interest in any natural m...,NaN,NaN,NaN,NaN,NaN,NaN,322,Kevin sheard,2/17,3/17,28.0,Multiple Sclerosis,x,NaN,NaN,3.0,upper arm,private,1,0.0,N,Y,Y,NaN,3.0,chest,private,Y,N,N,Y,Y,NaN,3,2 chest 1 neck,private,Y,N,N,Y,Y,0,P001,0.666667,1.466667,1.500000,0.666667,1.075000,0.0,0.25,0.4,0.0,0.0,0.0,1.333333,0.283333,70.6,0.000,54.833333,10.833333,20.00,31.253333,3.200000,5.536585,6.000000,6.000000,6.166667,4.857143,4.571429,5.714286
2,2,6/19/2023 13:37,6/19/2023 14:40,IP Address,76.188.214.194,100,3747,True,6/19/2023 14:40,R_PwEw1U2O3Uapejn,NaN,NaN,NaN,NaN,41.4481,-82.0177,anonymous,EN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,2,"1 - yes, that is true",3,"1 - yes, that is true",3,"1 - yes, that is true",3,5 - no that is not true,3,3,3,5 - no that is not true,"1 - yes, that is true",4,4,3,3,2,"I take more than 60 minutes to fall asleep, mo...",I do not wake up at night,"Most of the time, I awaken no more than 30 min...","I sleep no longer than 7-8 hours/night, withou...",I feel sad less than half the time,I feel irritable less than half the time,I feel anxious (tense) less than half the time,My mood brightens to a normal level which last...,My mood often relates to the time of day becau...,Night,No,The mood (internal feelings) that I experience...,There is no change in my usual appetite,NaN,I have not had a change in my weight,NaN,I occasionally feel indecisive or find that my...,I see myself as equally worthwhile and deservi...,I have an optimistic view of my future,I do not think of suicide or death,There is no change from usual in how intereste...,There is no change in my usual level of energy,I enjoy pleasurable activities just as much as...,My interest in sex is somewhat less than usual...,"I think, speak, and move at my usual rate of s...",I do not feel restless,I don't have any feeling of heaviness in my ar...,I don't have any of these symptoms: heart poun...,I have no spells of panic or specific fears (p...,There is no change in my usual bowel habits,"I have occasionally felt rejected, slighted, c...",I have not experienced the physical sensation ...,6,5,5,3,No,NaN,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,"Yes, cutting sugar and alcohol. I no longer dr...",NaN,NaN,NaN,NaN,NaN,"Yes, I haven’t gotten sick once since my first...","Yes, a lot. To name a few: \nNoticing my thoug...","Absolutely, I was facing Chemotherapy and stea...",I self serve and am very interested in becomin...,I teared up taking this survey. I cannot put i...,135,Kevin sheard,2/17,3/17,28.0,Multiple Sclerosis,x,NaN,NaN,3.0,upper arm,private,1,0.0,N,Y,Y,NaN,3.0,chest,private,Y,N,N,Y,Y,NaN,3,2 chest 1 neck,private,Y,N,N,Y,Y,0,P001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.466667,4.904762,5.857143,5.285714,5.285714,5.000000,4.000000,4.000000

In [8]:
# Start with a copy of the current DataFrame
df = df_ryff.copy()

# Define the MFI text-to-numeric mapping
mfi_map = {
    '1 - yes, that is true': 1,
    '2': 2,
    '3': 3,
    '4': 4,
    '5 - no that is not true': 5
}

# Identify all MFI columns
mfi_cols_raw = [col for col in df.columns if '| MFI_' in col]

# Define reverse-scored items in the MFI-20 (item numbers)
mfi_reverse_items = [1, 3, 4, 6, 7, 8, 11, 12, 15, 20]

# Subscale definitions (items 1-indexed)
mfi_subscales = {
    'General_Fatigue': [1, 5, 12, 16],
    'Physical_Fatigue': [2, 8, 14, 20],
    'Reduced_Activity': [10, 11, 17, 18],
    'Reduced_Motivation': [3, 6, 9, 15],
    'Mental_Fatigue': [4, 7, 13, 19]
}

# Map all responses to numeric
for col in mfi_cols_raw:
    df[col] = df[col].astype(str).str.strip().str.lower().map({k.lower(): v for k, v in mfi_map.items()})

# Reverse-score necessary items
reverse_cols = [col for col in mfi_cols_raw if any(col.strip().endswith(f'MFI_{i}') for i in mfi_reverse_items)]
for col in reverse_cols:
    df[col] = df[col].apply(lambda x: 6 - x if pd.notnull(x) else np.nan)

# Function to score subscales with 30% missing rule (min 3 of 4 items)
def score_mfi_subscale(df, subscale_items, output_col, min_valid=3):
    cols = [col for col in mfi_cols_raw if any(col.strip().endswith(f'MFI_{i}') for i in subscale_items)]
    item_data = df[cols].astype(float)
    valid_counts = item_data.notna().sum(axis=1)
    mean_score = item_data.mean(axis=1)
    df[output_col] = mean_score.where(valid_counts >= min_valid)
    return df

# Score each MFI subscale
for subscale, items in mfi_subscales.items():
    df = score_mfi_subscale(df, items, f'MFI_{subscale}_Score')

# Compute total score if all 5 subscales are present
subscale_score_cols = [f'MFI_{s}_Score' for s in mfi_subscales]
df['MFI_TotalScore'] = df[subscale_score_cols].mean(axis=1).where(df[subscale_score_cols].notna().all(axis=1))

# Drop raw MFI item columns
df_clean = df.drop(columns=mfi_cols_raw, errors='ignore')

# Export cleaned dataframe
df_clean.to_csv("Kambo_with_MFI_clean.csv", index=False)

In [9]:
# Define item-specific response mappings for IDS-SR
ids_mappings = {
    'FALLING ASLEEP: | IDS.1.': {
        'i never take longer than 30 minutes to fall asleep': 0,
        'i take at least 30 minutes to fall asleep, less than half the time': 1,
        'i take at least 30 minutes to fall asleep, more than half the time': 2,
        'i take more than 60 minutes to fall asleep, more than half the time': 3
    },
    'SLEEP DURING THE NIGHT: | IDS.2.': {
        'i do not wake up at night': 0,
        'i wake up at least once a night, but i go back to sleep easily': 1,
        'i have a restless, light sleep with a few brief awakenings each night': 2,
        'i awaken more than once a night and stay awake for 20 minutes or more, more than half the time': 3
    },
    'WAKING UP TOO EARLY: | IDS.3.': {
        'more than half the time, i awaken more than 30 minutes before i need to get up': 0,
        'more than half the time, i awaken more than 30 minutes before i need to and stay awake': 1,
        'most of the time, i awaken no more than 30 minutes before i need to get up': 1,
        'i almost always awaken at least one hour or so before i need to, but i go back to sleep eventually': 2,
        "i awaken at least one hour before i need to, and can't go back to sleep": 3
    },
    'SLEEPING TOO MUCH: | IDS.4.': {
        'i sleep no longer than 7-8 hours/night, without napping during the day': 0,
        'i sleep no longer than 10 hours in a 24-hour period including naps': 1,
        'i sleep no longer than 12 hours in a 24-hour period including naps': 2,
        'i sleep longer than 12 hours in a 24-hour period including naps': 3
    },
    'FEELING SAD: | IDS.5.': {
        'i do not feel sad': 0,
        'i feel sad less than half the time': 1,
        'i feel sad more than half the time': 2,
        'i feel sad nearly all of the time': 3
    },
    'FEELING IRRITABLE: | IDS.6.': {
        'i do not feel irritable': 0,
        'i feel irritable less than half the time': 1,
        'i feel irritable more than half the time': 2,
        'i feel extremely irritable nearly all of the time': 3
    },
    'FEELING ANXIOUS OR TENSE: | IDS.7.': {
        'i do not feel anxious or tense': 0,
        'i feel anxious (tense) less than half the time': 1,
        'i feel anxious (tense) more than half the time': 2,
        'i feel extremely anxious (tense) nearly all of the time': 3
    },
    'RESPONSE OF YOUR MOOD TO GOOD OR DESIRED EVENTS: | IDS.8.': {
        'my mood brightens to a normal level which lasts for several hours when good events occur': 0,
        'my mood brightens but i do not feel like my normal self when good events occur': 1,
        'my mood brightens only somewhat to a rather limited range of desired events': 2,
        'my mood does not brighten at all, even when very good or desired events occur in my life': 3
    },
    'MOOD IN RELATION TO THE TIME OF DAY: | IDS.9.': {
        'there is no regular relationship between my mood and the time of day': 0,
        'my mood often relates to the time of day because of environmental events (e.g., being alone, working)': 1,
        'in general, my mood is more related to the time of day than to environmental events': 2,
        'my mood is clearly and predictably better or worse at a particular time each day': 3
    },
    'MY MOOD IS TYPICALLY WORSE IN THE... | IDS.9A.': {
        'morning': 1,
        'afternoon': 0,
        'evening': 0,
        'night': 0,
        'does not vary': 0
    },
    # The rest will be continued in the next block to keep it structured
}

# Show how many mappings have been defined so far
len(ids_mappings)

10

In [10]:
# Continue defining mappings for IDS items 11–30
ids_mappings.update({
    'IS YOUR MOOD VARIATION ATTRIBUTED TO ENVIRONMENT? | IDS.9B.': {
        'no': 0,
        'yes': 1
    },
    'THE QUALITY OF YOUR MOOD: | IDS.10.': {
        'the mood (internal feelings) that i experience is very much a normal mood': 0,
        'my mood is sad, but this sadness is different from the type of sadness associated with grief or loss': 1,
        'my mood is sad, but this sadness has a rather different quality to it than the sadness i would feel if someone close to me died or left': 2,
        'my mood is sad, but this sadness is pretty much like the sad mood i would feel if someone close to me died or left': 3
    },
    'DECREASED APPETITE: | IDS.11.': {
        'there is no change in my usual appetite': 0,
        'i eat somewhat less often or lesser amounts of food than usual': 1,
        'i eat much less than usual and only with personal effort': 2,
        'i rarely eat within a 24-hour period, and only with extreme personal effort or when others persuade me to eat': 3
    },
    'INCREASED APPETITE: | IDS.12.': {
        'there is no change from my usual appetite': 0,
        'i feel a need to eat more frequently than usual': 1,
        'i regularly eat more often and/or greater amounts of food than usual': 2,
        'i feel driven to overeat both at mealtime and between meals': 3
    },
    'DECREASED WEIGHT (WITHIN THE LAST TWO WEEKS): | IDS.13.': {
        'i have not had a change in my weight': 0,
        "i feel as if i've had a slight weight loss": 1,
        'i have lost 2 pounds or more': 2,
        'i have lost 5 pounds or more': 3
    },
    'INCREASED WEIGHT (WITHIN THE LAST TWO WEEKS): | IDS.14.': {
        'i have not had a change in my weight': 0,
        "i feel as if i've had a slight weight gain": 1,
        'i have gained 2 pounds or more': 2,
        'i have gained 5 pounds or more': 3
    },
    'CONCENTRATION/DECISION MAKING: | IDS.15.': {
        'there is no change in my usual capacity to concentrate or make decisions': 0,
        'i occasionally feel indecisive or find that my attention wanders': 1,
        'most of the time, i struggle to focus my attention or to make decisions': 2,
        'i cannot concentrate well enough to read or cannot make even minor decisions': 3
    },
    'VIEW OF MYSELF: | IDS.16.': {
        'i see myself as equally worthwhile and deserving as other people': 0,
        'i am more self-blaming than usual': 1,
        'i largely believe that i cause problems for other': 2,
        'i think almost constantly about major and minor defects in myself': 3
    },
    'VIEW OF MY FUTURE | IDS.17.': {
        'i have an optimistic view of my future': 0,
        'i am occasionally pessimistic about my future, but for the most part i believe things will get better': 1,
        "i'm pretty certain that my immediate future (1-2 months) does not hold much promise of good things for me": 2,
        'i see no hope of anything good happening to me anytime in the future': 3
    },
    'THOUGHTS OF DEATH OR SUICIDE: | IDS.18.': {
        'i do not think of suicide or death': 0,
        "i feel that life is empty or wonder if it's worth living": 1,
        'i think of suicide or death several times a week for several minutes': 2,
        'i think of suicide or death several times a day in some detail, or have made plans': 3
    },
    'GENERAL INTEREST: | IDS.19.': {
        'there is no change from usual in how interested i am in other people or activities': 0,
        'i notice that i am less interested in people or activities': 1,
        'i find i have interest in only one or two of my formerly pursued activities': 2,
        'i have virtually no interest in formerly pursued activities': 3
    },
    'ENERGY LEVELS: | IDS.20.': {
        'there is no change in my usual level of energy': 0,
        'i get tired more easily than usual': 1,
        'i have to make a big effort to start or finish my usual daily activities (for example, shopping, homework, cooking, or going to work)': 2,
        "i really cannot carry out most of my usual daily activities because i just don't have the energy": 3
    },
    'CAPACITY FOR PLEASURE OR ENJOYMENT (EXCLUDING SEX): | IDS.21.': {
        'i enjoy pleasurable activities just as much as usual': 0,
        'i do not feel my usual sense of enjoyment from pleasurable activities': 1,
        'i rarely get a feeling of pleasure from any activity': 2,
        'i am unable to get any pleasure or enjoyment from anything': 3
    },
    'INTEREST IN SEX (PLEASE RATE INTEREST, NOT ACTIVITY): | IDS.22.': {
        "i'm just as interested in sex as usual": 0,
        'my interest in sex is somewhat less than usual or i do not get the same pleasure from sex as i used to': 1,
        'i have little desire for or rarely derive pleasure from sex': 2,
        'i have absolutely no interest in or derive no pleasure from sex': 3
    },
    'FEELING SLOWED DOWN: | IDS.23.': {
        'i think, speak, and move at my usual rate of speed': 0,
        'i find that my thinking is slowed down or my voice sounds dull or flat': 1,
        "it takes me several seconds to respond to most questions and i'm sure my thinking is slowed": 2,
        'i am often nonresponsive to questions or require coaxing to continue': 3
    },
    'FEELING RESTLESS: | IDS.24.': {
        'i do not feel restless': 0,
        'i have impulses to move about and am quite restless': 1,
        "i'm often fidgety, wring my hands, or need to shift how i am sitting": 2,
        'at times, i am unable to stay seated and need to pace around': 3
    },
    'ACHES AND PAINS: | IDS.25.': {
        "i don't have any feeling of heaviness in my arms or legs and don't have any aches or pains": 0,
        "sometimes i get headaches or pains in my stomach, back or joints but these pains are only sometimes present and they don't stop me from doing what i need to do": 1,
        'i have these sorts of pains most of the time': 2,
        'these pains are so bad they force me to stop what i am doing': 3
    },
    'OTHER BODILY SYMPTOMS: | IDS.26.': {
        "i don't have any of these symptoms: heart pounding fast, blurred vision, sweating, hot and cold flashes, chest pain, heart turning over in my chest, ringing in my ears, or shaking": 0,
        'i have some of these symptoms but they are mild and are present only sometimes': 1,
        'i have several of these symptoms and they bother me quite a bit': 2,
        'i am constantly experiencing physical distress': 3
    },
    'PANIC/PHOBIC SYMPTOMS: | IDS.27.': {
        'i have no spells of panic or specific fears (phobias) (such as animals or heights)': 0,
        'i have mild panic episodes or fears that do not usually change my behavior or stop me from functioning': 1,
        'i have significant panic episodes or fears that force me to change my behavior but do not stop me from functioning': 2,
        'i have panic episodes at least once a week or severe fears that stop me from carrying on my daily activities': 3
    },
    'CONSTIPATION/DIARRHEA: | IDS.28.': {
        'there is no change in my usual bowel habits': 0,
        'i have intermittent constipation or diarrhea, which is mild': 1,
        'i have diarrhea or constipation most of the time but it does not interfere with my day-to-day functioning': 2,
        'i have constipation or diarrhea for which i take medicine or which interferes with my day-to-day activities': 3
    },
    'INTERPERSONAL SENSITIVITY: | IDS.29.': {
        'i have not felt easily rejected, slighted, criticized, or hurt by others at all': 0,
        'i have occasionally felt rejected, slighted, criticized, or hurt by others': 1,
        'i have often felt rejected, slighted, criticized, or hurt by others, but these feelings have had only slight effects on my relationships or work': 2,
        'i have often felt rejected, slighted, criticized, or hurt by others and these feelings have impaired my relationships and work': 3
    },
    'LEADEN PARALYSIS/PHYSICAL ENERGY: | IDS.30.': {
        'i have not experienced the physical sensation of feeling weighted down and without physical energy': 0,
        'i have occasionally experienced periods of feeling physically weighted down and without physical energy, but without a negative effect on work, school, or activity level': 1,
        'i feel physically weighted down (without physical energy) more than half the time': 2,
        'i feel physically weighted down (without physical energy) most of the time, several hours per day, several days per week': 3
    }
})

# Confirm that all 32 items now have mappings
len(ids_mappings)

32

In [11]:
# Apply item-specific mappings to the IDS dataset
df_ids_scored = df_clean.copy()

# Normalize and score each column using the pre-defined mapping
for col, mapping in ids_mappings.items():
    df_ids_scored[col] = (
    df_ids_scored[col]
      .astype(str)
      .str.strip()
      .str.lower()
      .str.replace(r"[‘’´`]", "'", regex=True)  # Normalize all odd apostrophes to plain '
     .replace(mapping)
    )

ids_columns = list(ids_mappings.keys())

# Recalculate TotalScore from just the IDS columns
valid_counts = df_ids_scored[ids_columns].notna().sum(axis=1)
df_ids_scored[ids_columns] = df_ids_scored[ids_columns].apply(pd.to_numeric, errors='coerce')
df_ids_scored['IDS_TotalScore'] = df_ids_scored[ids_columns].sum(axis=1).where(valid_counts >= 22)

# Drop raw item columns
df_ids_cleaned = df_ids_scored.drop(columns=ids_columns, errors='ignore')

# Export
df_ids_cleaned.to_csv("Kambo_with_IDS_clean.csv", index=False)

In [12]:
df_ids_cleaned.head()

,Unnamed: 0,START DATE | STARTDATE,END DATE | ENDDATE,RESPONSE TYPE | STATUS,IP ADDRESS | IPADDRESS,PROGRESS,DURATION (IN SECONDS),FINISHED,RECORDED DATE | RECORDEDDATE,RESPONSE ID | RESPONSEID,RECIPIENT LAST NAME | RECIPIENTLASTNAME,RECIPIENT FIRST NAME | RECIPIENTFIRSTNAME,RECIPIENT EMAIL | RECIPIENTEMAIL,EXTERNAL DATA REFERENCE | EXTERNALREFERENCE,LOCATION LATITUDE | LOCATIONLATITUDE,LOCATION LONGITUDE | LOCATIONLONGITUDE,DISTRIBUTION CHANNEL | DISTRIBUTIONCHANNEL,USER LANGUAGE | USERLANGUAGE,WHAT IS THE NAME OF THE PRACTITIONER YOU WILL BE WORKING WITH? | GEN.1.,WHAT IS THE DATE OF YOUR 1ST SCHEDULED KAMBO SESSION? | GEN.2.,WHAT IS THE DATE OF YOUR 3RD SCHEDULED KAMBO SESSION? | GEN.3.,WHAT IS YOUR AGE? | DEMO.1.,WHAT BIOLOGICAL SEX WERE YOU ASSIGNED AT BIRTH? | DEMO.2.,WHAT GENDER DO YOU IDENTIFY WITH? - SELECTED CHOICE | DEMO.3.,WHAT GENDER DO YOU IDENTIFY WITH? - OTHER - TEXT | DEMO.3._7_TEXT,WHAT RACE DO YOU IDENTIFY AS? | DEMO.4.,WHAT IS YOUR HIGHEST LEVEL OF EDUCATION COMPLETED? | DEMO.5.,WHAT IS YOUR GROSS HOUSEHOLD INCOME? | DEMO.6.,"WHAT IS YOUR APPROXIMATE HEIGHT (FT, IN)? | DEMO.7.",WHAT IS YOUR APPROXIMATE WEIGHT (LBS)? | DEMO.8.,HAVE YOU BEEN DIAGNOSED WITH ANY MEDICAL CONDITIONS OR DISEASE? DO YOU CURRENTLY DEAL WITH THESE CONDITIONS OR HAVE YOU RECOVERED FROM THESE CONDITIONS? PLEASE EXPLAIN. | DEMO.9.,HAVE YOU BEEN DIAGNOSED WITH LYME DISEASE BY A LICENSED HEALTHCARE PROFESSIONAL? | DEMO.10.,HAVE YOU BEEN DIAGNOSED WITH POST-TREATMENT LYME SYNDROME BY A LICENSED HEALTHCARE PROFESSIONAL? | DEMO.11.,"PLEASE LIST ANY DRUGS, MEDICATIONS, OR SUPPLEMENTS YOU ARE CURRENTLY TAKING. | DEMO.12.","HAVE YOU EVER USED A PSYCHEDELIC SUBSTANCE SUCH AS LSD, PSILOCYBIN (MAGIC) MUSHROOMS, MESCALINE (PEYOTE), DMT, OR AYAHUASCA? | DEMO.13.",DO YOU USE CANNABIS? | DEMO.14.,WHAT ARE THE REASONS YOU HAVE SOUGHT OUT KAMBO? | DEMO.15.,PLEASE SELECT THE OPTION THAT REFLECTS HOW NERVOUS YOU ARE FEELING ABOUT YOUR UPCOMING KAMBO EXPERIENCES. | DEMO.16.,PLEASE SELECT THE OPTION THAT REFLECTS HOW EXCITED YOU ARE FEELING ABOUT YOUR UPCOMING KAMBO EXPERIENCES. | DEMO.17.,"IN GENERAL, I CONSIDER MYSELF: | SHS.1","COMPARED WITH MOST OF MY PEERS, I CONSIDER MYSELF: | SHS.2","SOME PEOPLE ARE GENERALLY VERY HAPPY. THEY ENJOY LIFE REGARDLESS OF WHAT IS GOING ON, \r\nGETTING THE MOST OUT OF EVERYTHING. TO WHAT EXTENT DOES THIS CHARACTERIZATION DESCRIBE YOU? | SHS.3","SOME PEOPLE ARE GENERALLY NOT VERY HAPPY. ALTHOUGH THEY ARE NOT DEPRESSED, THEY NEVER \r\nSEEM AS HAPPY AS THEY MIGHT BE. TO WHAT EXTENT DOES THIS CHARACTERIZATION DESCRIBE YOU? | SHS.4","THROUGHOUT OUR LIVES, MOST OF US HAVE HAD PAIN FROM TIME TO TIME\n(SUCH AS MINOR HEADACHES, SPRAINS, AND TOOTHACHES). HAVE YOU HAD\nPAIN OTHER THAN THESE EVERYDAY KINDS OF PAIN DURING THE LAST WEEK? - SELECTED CHOICE | BPI.1.","THROUGHOUT OUR LIVES, MOST OF US HAVE HAD PAIN FROM TIME TO TIME\n(SUCH AS MINOR HEADACHES, SPRAINS, AND TOOTHACHES). HAVE YOU HAD\nPAIN OTHER THAN THESE EVERYDAY KINDS OF PAIN DURING THE LAST WEEK? - YES (PLEASE SPECIFY) - TEXT | BPI.1._1_TEXT",DID YOU TAKE PAIN MEDICATIONS IN THE LAST 7 DAYS? | BPI.1A.,I FEEL I HAVE HAD SOME PAIN THAT REQUIRES MEDICATION EACH AND EVERY DAY | BPI.1B.,PLEASE RATE YOUR PAIN ACCORDING TO THE FOLLOWING STATEMENTS: - PLEASE RATE YOUR PAIN BY FILLING IN THE ONE NUMBER THAT BEST DESCRIBES YOUR PAIN AT ITS WORST IN THE PAST 24 HOURS. | BPI.3._1,PLEASE RATE YOUR PAIN ACCORDING TO THE FOLLOWING STATEMENTS: - PLEASE RATE YOUR PAIN BY FILLING IN THE ONE NUMBER THAT BEST DESCRIBES YOUR PAIN AT ITS LEAST IN THE PAST 24 HOURS | BPI.3._2,PLEASE RATE YOUR PAIN ACCORDING TO THE FOLLOWING STATEMENTS: - PLEASE RATE YOUR PAIN BY FILLING IN THE ONE NUMBER THAT BEST DESCRIBES YOUR PAIN ON THE AVERAGE. | BPI.3._3,WHAT TREATMENTS OR MEDICATIONS ARE YOU RECEIVING FOR YOUR PAIN? | BPI.4.,"IN THE PAST 24 HOURS, HOW MUCH RELIEF HAVE PAIN TREATMENTS OR \nMEDICATIONS PROVIDED? PLEASE SELECT THE ONE PERCENTAGE THAT MOST\nSHOWS HOW MUCH RELIEF YOU HAVE RECEIVED. | BPI.5.","SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - GENERAL ACTIVITY | BPI.6._1","SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - MOOD | BPI.6._2","SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - WALKING ABILITY | BPI.6._3","SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - NORMAL WORK (INCLUDES BOTH WORK OUTSIDE THE HOME AND HOUSEWORK) | BPI.6._4","SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - RELATION WITH OTHER PEOPLE | BPI.6._5","SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - SLEEP | BPI.6._6","SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - ENJOYMENT OF LIFE | BPI.6._7",Phase,1.\tPLEASE BRIEFLY DESCRIBE YOUR EXPERIENCE IN THE KAMBO RITUAL: | QUAL.1.,2. WERE THERE SPECIFIC ASPECTS OF THE RITUAL THAT WERE PARTICULARLY VALUABLE? | QUAL.2.,3.\tWERE THERE SPECIFIC ASPECTS OF THE RITUAL THAT WERE PARTICULARLY CHALLENGING? | QUAL.3.,DID YOU EXPERIENCE ANY EMOTIONAL ELEMENTS OF THE KAMBO RITUAL? | QUAL.4.,5.\tDID YOU EXPERIENCE ANY SPIRITUAL ELEMENTS OF THE KAMBO RITUAL? | QUAL.5.,6.\tWHAT WERE THE REASONS YOU SOUGHT OUT KAMBO AND DID THE PROCESS SATISFY THEM? | QUAL 6.,"ON THE FOLLOWING PAGES YOU WILL FIND A NUMBER OF STATEMENTS AND BELOW EACH \nSTATEMENT A LINE WITH THE ENDPOINTS “NO, NOT MORE THAN USUALLY” AND “YES, MUCH MORE \nTHAN USUALLY.” THE LINE REPRESENTS SOMETHING LIKE A THERMOMETER THAT WILL BE USED TO \nASSESS ALTERATIONS FROM YOUR NORMAL WAKING CONSCIOUSNESS.\n\n\nPLEASE RATE TO WHAT EXTENT THE STATEMENTS APPLY TO YOUR PARTICULAR EXPERIENCE –\nCOMPARED TO NORMAL WAKING CONSCIOUSNESS – BY USING THE SLIDER ON THE LINE \nNEXT TO THE STATEMENTS.\n\n\nPLEASE NOTE THAT YOUR NORMAL WAKING CONSCIOUSNESS CORRESPONDS TO A MARK AT THE \nVERY LEFT END OF THE SCALE, I.E.: “NO, NOT MORE THAN USUALLY.” | INSTRUCTIONS","1.\tHAVE ANY OF THE PHYSICAL, EMOTIONAL OR SPIRITUAL EFFECTS FROM THE KAMBO PROCESS PERSISTED UNTIL THIS POINT? | QUAL.1.",3.\tDO YOU FEEL THAT THERE ARE ANY LASTING CHANGES FROM HAVING DONE KAMBO? | QUAL.3.,4. DID KAMBO HAVE ANY IMPACT ON YOUR LIFE? PLEASE DESCRIBE. | QUAL.4.,5.\tDO YOU HAVE THE INTENTION TO DO KAMBO AGAIN AT SOME POINT IN YOUR LIFE? WHY OR WHY NOT? | QUAL.5.,6.\tIS THERE ANYTHING ELSE YOU'D LIKE TO SHARE WITH US? | QUAL 6.,non_null_count,practitioner,scheduled session 1,scheduled session 3,Days btwn,Health diagnosis,Autoimmu,Meds,Session 1,# of points,location of points,Private or group,vomit,BM,Fainting,Rapeh,Sananga,Session 2,# of points.1,location of points.1,Private or group.1,vomit.1,BM.1,Fainting.1,Rapeh.1,Sananga.1,Session 3,# of points.2,location of points.2,Private or group.2,vomit.2,BM.2,Fainting.2,Rapeh.2,Sananga.2,Private_or_group_numeric,AnonID,MEQ30_Ineffability,MEQ30_MysticalExperience,MEQ30_PositiveMood,MEQ30_TranscendenceOfTimeAndSpace,MEQ30_TotalScore,CEQ30_Isolation_SUM,CEQ30_Fear_SUM,CEQ30_Grief_SUM,CEQ30_Insanity_SUM,CEQ30_Death_SUM,CEQ30_Paranoia_SUM,CEQ30_PhysicalDistress_SUM,CEQ30_Total_SUM,5DASC_OceanicBoundlessness_Score,5DASC_AnxiousEgoDissolution_Score,5DASC_VisionaryRestructuralization_Score,5DASC_AuditoryAlterations_Score,5DASC_ReductionOfVigilance_Score,5DASC_TotalScore,MAAS_Total,RYFF_Total,RYFF_Autonomy_Score,RYFF_EnvironmentalMastery_Score,RYFF_PersonalGrowth_Score,RYFF_PositiveRelations_Score,RYFF_PurposeInLife_Score,RYFF_SelfAcceptance_Score,MFI_General_Fatigue_Score,MFI_Physical_Fatigue_Score,MFI_Reduced_Activity_Score,MFI_Reduced_Motivation_Score,MFI_Mental_Fatigue_Score,MFI_TotalScore,IDS_TotalScore
0,0,2023-02-16 20:16:10,2023-02-16 21:05:37,IP Address,76.181.171.194,100,2966,True,2023-02-16 21:05:38,R_stm7DF0q0ZkFcoF,NaN,NaN,NaN,NaN,41.2463,-81.8310,anonymous,EN,Kevin Sheard,2/17/23,3/17/23,28.0,Female,Cis-Female,NaN,Other,"University (e.g., bachelor’s degree)","$25,000-$50,000 annually",5’3”,119,Multiple Sclerosis. Mostly recovered. Only dea...,No,No,Vit D/ fish oil/ brown seaweed,Yes,Often,I heard it could be beneficial for those with ...,6,Extremely excited,6,4,4,4,Yes (please specify),Intermittent back pain,No,No,4,0 - No Pain,3,Red light therapy/ icy hot,90%,0 - Does not interfere,3,0 - Does not interfere,4,2,0 - Does not interfere,0 - Does not interfere,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,162,Kevin sheard,2/17,3/17,28.0,Multiple Sclerosis,x,NaN,NaN,3.0,upper arm,private,1,0.0,N,Y,Y,NaN,3.0,chest,private,Y,N,N,Y,Y,NaN,3,2 chest 1 neck,private,Y,N,N,Y,Y,0,P001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.400000,4.976190,5.428571,4.857143,5.857143,4.571429,4.000000,5.142857,2.25,4.25,4.25,4.00,3.00,3.55,18.0
1,1,3/22/2023 10:03,3/22/2023 11:26,IP Address,76.188.214.194,100,4965,True,3/22/2023 11:26,R_3CCuL24AWuFvoqH,NaN,NaN,NaN,NaN,41.4481,-82.0177,anonymous,EN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,4,5,3,No,NaN,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,My experience in the ritual was more miles tha...,The music Kevin played alleviated anxiety and ...,The sananga and hapé were more challenging tha...,"Yes, the second session started emotionally be...","Yes! After doing Kambò I started, noticing my ...",I have always had an interest in any natural m...,NaN,NaN,NaN,NaN,NaN,NaN,322,Kevin sheard,2/17,3/17,28.0,Multiple Sclerosis,x,NaN,NaN,3.0,upper arm,private,1,0.0,N,Y,Y,NaN,3.0,chest,private,Y,N,N,Y,Y,NaN,3,2 chest 1 neck,private,Y,N,N,Y,Y,0,P001,0.666667,1.466667,1.500000,0.666667,1.075000,0.0,0.25,0.4,0.0,0.0,0.0,1.333333,0.283333,70.6,0.000,54.833333,10.833333,20.00,31.253333,3.200000,5.536585,6.000000,6.000000,6.166667,4.857143,4.571429,5.714286,2.50,4.50,4.50,4.25,3.25,3.80,13.0
2,2,6/19/2023 13:37,6/19/2023 14:40,IP Address,76.188.214.194,100,3747,True,6/19/2023 14:40,R_PwEw1U2O3Uapejn,NaN,NaN,NaN,NaN,41.4481,-82.0177,anonymous,EN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6,5,5,3,No,NaN,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,"Yes, cutting sugar and alcohol. I no longer dr...",NaN,NaN,NaN,NaN,NaN,"Yes, I haven’t gotten sick once since my first...","Yes, a lot. To name a few: \nNoticing my thoug...","Absolutely, I was facing Chemotherapy and stea...",I self serve and am very interested in becomin...,I teared up taking this survey. I cannot put i...,135,Kevin sheard,2/17,3/17,28.0,Multiple Sclerosis,x,NaN,NaN,3.0,upper arm,private,1,0.0,N,Y,Y,NaN,3.0,chest,private,Y,N,N,Y,Y,NaN,3,2 chest 1 neck,private,Y,N,N,Y,Y,0,P001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.466667,4.904762,5.857143,5.285714,5.285714,5.000000,4.000000,4.000000,3.50,4.00,3.75,4.25,3.50,3.80,11.0
3,3,2023-02-16 20:01:21,2023-02-17 12:55:01,IP Address,174.216.50.49,100,60820,True,2023-02-17 12:55:02,R_UsXoVyTDkjEeRPz,NaN,NaN,NaN,NaN,39.9458,-74.9042,anonymous,EN,Nicole O’Malley,2/17/2023,3/4 or 3/11 we have not worked out the date yet,45.0,Female,Cis-Female,NaN,"Caucasian / White (e.g., German, Irish, Englis...",High school,"$50,000-$75,000 annually","5'3""",185,Alopecia areata that has developed into alopec...,No,No,"Levocetirizine 5mg, Montelukast 10mg, Symbicor...",Yes,Daily,"My autoimmune, Alopecia, but have wanted to si...",6,8,2,2,1 - Not at all,5,No,NaN,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,149,Nikki O malley,2/17,March 18,29.0,"alopecia universalis, previous breast cancer",x,"Levocetirizine, Prilosec, Albuterol as needed",NaN,5.0,"chakra- 1 throat, 2 heart, 2 solar",group,1,1.0,N,Y,Y,NaN,7.0,upper arm,group,Y,Y,N,Y,Y,NaN,8,auricular,group,Y,N,N,Y,Y,2,P002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.600000,3.976190,2.714286,2.857143,3.714286,5.000000,5.428571,4.142857,1.75,1.75,1.50,2.25,2.00,1.85,39.0
4,4,3/24/2023 8:08,3/24/2023 14:08,IP Address,104.129.205.6,100,21572,True,3/24/2023 14:08,R_2RXuEgPN1tbY4T6,NaN,NaN,NaN,NaN,35.2296,-80.8430,anonymous,EN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,1 - Less happy,2,3,No,NaN,Yes,No,1,0 - No Pain,1,Advil for minor headaches,100% - Complete Relief,0 - Does not interfere,2,0 - Does not interfere,0 - Does not interfere,0 - Does not interfere,1,1,2,"The experience was intense, but also amazing w...",I think being introduced to Rapé. I will seek...,I felt that my first session was the easiest a...,Yes. I felt it brought up many emotions.,I think every Kambo ritual is a spiritual expe...,I meet Nikki new years eve 2019/2020 and have ...,NaN,NaN,NaN,NaN,NaN,NaN,330,Nikki O malley,2/17,March 18,29.0,"alopecia universalis, previous breast cancer",x,"Levocetirizine, Prilosec, Albuterol as needed",NaN,5.0,"chakra- 1 throat, 2 heart, 2 solar",group,1,1.0,N,Y,Y,NaN,7.0,upper arm,group,Y,Y,N,Y,Y,NaN,8,auricular,group,Y,N,N,Y,Y,2,P002,2.333333,1.066667,2.333333,0.500000,1.558333,0.0,0.60,0.6,0.0,0.0,0.0,1.500000,0.385714,19.5,1.875,1.600000,0.000000,21.25,8.845000,3.066667,4.238095,4.000000,3.571429,4.428571,4.285714,4.714286,4.428571,2.75,1.25,2.50,2.75,2.75,2.40,22.0

In [13]:
# We'll assume df_ids_cleaned is the working dataframe with SHS items
df_shs = df_ids_cleaned.copy()

# Define SHS columns
shs_cols = [
    'IN GENERAL, I CONSIDER MYSELF: | SHS.1',
    'COMPARED WITH MOST OF MY PEERS, I CONSIDER MYSELF: | SHS.2',
    'SOME PEOPLE ARE GENERALLY VERY HAPPY. THEY ENJOY LIFE REGARDLESS OF WHAT IS GOING ON, \r\nGETTING THE MOST OUT OF EVERYTHING. TO WHAT EXTENT DOES THIS CHARACTERIZATION DESCRIBE YOU? | SHS.3',
    'SOME PEOPLE ARE GENERALLY NOT VERY HAPPY. ALTHOUGH THEY ARE NOT DEPRESSED, THEY NEVER \r\nSEEM AS HAPPY AS THEY MIGHT BE. TO WHAT EXTENT DOES THIS CHARACTERIZATION DESCRIBE YOU? | SHS.4'
]

# Build a generic mapping for responses 1–7, regardless of label
shs_map = {
    '1 - not a very happy person': 1,
    '1 - less happy': 1,
    '1 - not at all': 1,
    '2': 2,
    '3': 3,
    '4': 4,
    '5': 5,
    '6': 6,
    '7 - a very happy person': 7,
    '7 - more happy': 7,
    '7 - a great deal': 7
}

# Normalize and apply mapping to all SHS columns
for col in shs_cols:
    df_shs[col] = (
        df_shs[col]
        .astype(str)
        .str.strip()
        .str.lower()
        .replace(shs_map)
    )

# Convert all SHS values to numeric (some may still be unconverted strings)
df_shs[shs_cols] = df_shs[shs_cols].apply(pd.to_numeric, errors='coerce')

# Reverse score SHS.4: 8 - x
df_shs[shs_cols[-1]] = df_shs[shs_cols[-1]].apply(lambda x: 8 - x if pd.notnull(x) else np.nan)

# Compute SHS total only if at least 3 of 4 items are present
valid_counts = df_shs[shs_cols].notna().sum(axis=1)
df_shs['SHS_TotalScore'] = df_shs[shs_cols].mean(axis=1).where(valid_counts >= 3)

# Drop raw SHS columns
df_shs_cleaned = df_shs.drop(columns=shs_cols, errors='ignore')

# Export final version
df_shs_cleaned.to_csv("Kambo_with_SHS_scored.csv", index=False)

In [14]:
df_shs_cleaned.head()

,Unnamed: 0,START DATE | STARTDATE,END DATE | ENDDATE,RESPONSE TYPE | STATUS,IP ADDRESS | IPADDRESS,PROGRESS,DURATION (IN SECONDS),FINISHED,RECORDED DATE | RECORDEDDATE,RESPONSE ID | RESPONSEID,RECIPIENT LAST NAME | RECIPIENTLASTNAME,RECIPIENT FIRST NAME | RECIPIENTFIRSTNAME,RECIPIENT EMAIL | RECIPIENTEMAIL,EXTERNAL DATA REFERENCE | EXTERNALREFERENCE,LOCATION LATITUDE | LOCATIONLATITUDE,LOCATION LONGITUDE | LOCATIONLONGITUDE,DISTRIBUTION CHANNEL | DISTRIBUTIONCHANNEL,USER LANGUAGE | USERLANGUAGE,WHAT IS THE NAME OF THE PRACTITIONER YOU WILL BE WORKING WITH? | GEN.1.,WHAT IS THE DATE OF YOUR 1ST SCHEDULED KAMBO SESSION? | GEN.2.,WHAT IS THE DATE OF YOUR 3RD SCHEDULED KAMBO SESSION? | GEN.3.,WHAT IS YOUR AGE? | DEMO.1.,WHAT BIOLOGICAL SEX WERE YOU ASSIGNED AT BIRTH? | DEMO.2.,WHAT GENDER DO YOU IDENTIFY WITH? - SELECTED CHOICE | DEMO.3.,WHAT GENDER DO YOU IDENTIFY WITH? - OTHER - TEXT | DEMO.3._7_TEXT,WHAT RACE DO YOU IDENTIFY AS? | DEMO.4.,WHAT IS YOUR HIGHEST LEVEL OF EDUCATION COMPLETED? | DEMO.5.,WHAT IS YOUR GROSS HOUSEHOLD INCOME? | DEMO.6.,"WHAT IS YOUR APPROXIMATE HEIGHT (FT, IN)? | DEMO.7.",WHAT IS YOUR APPROXIMATE WEIGHT (LBS)? | DEMO.8.,HAVE YOU BEEN DIAGNOSED WITH ANY MEDICAL CONDITIONS OR DISEASE? DO YOU CURRENTLY DEAL WITH THESE CONDITIONS OR HAVE YOU RECOVERED FROM THESE CONDITIONS? PLEASE EXPLAIN. | DEMO.9.,HAVE YOU BEEN DIAGNOSED WITH LYME DISEASE BY A LICENSED HEALTHCARE PROFESSIONAL? | DEMO.10.,HAVE YOU BEEN DIAGNOSED WITH POST-TREATMENT LYME SYNDROME BY A LICENSED HEALTHCARE PROFESSIONAL? | DEMO.11.,"PLEASE LIST ANY DRUGS, MEDICATIONS, OR SUPPLEMENTS YOU ARE CURRENTLY TAKING. | DEMO.12.","HAVE YOU EVER USED A PSYCHEDELIC SUBSTANCE SUCH AS LSD, PSILOCYBIN (MAGIC) MUSHROOMS, MESCALINE (PEYOTE), DMT, OR AYAHUASCA? | DEMO.13.",DO YOU USE CANNABIS? | DEMO.14.,WHAT ARE THE REASONS YOU HAVE SOUGHT OUT KAMBO? | DEMO.15.,PLEASE SELECT THE OPTION THAT REFLECTS HOW NERVOUS YOU ARE FEELING ABOUT YOUR UPCOMING KAMBO EXPERIENCES. | DEMO.16.,PLEASE SELECT THE OPTION THAT REFLECTS HOW EXCITED YOU ARE FEELING ABOUT YOUR UPCOMING KAMBO EXPERIENCES. | DEMO.17.,"THROUGHOUT OUR LIVES, MOST OF US HAVE HAD PAIN FROM TIME TO TIME\n(SUCH AS MINOR HEADACHES, SPRAINS, AND TOOTHACHES). HAVE YOU HAD\nPAIN OTHER THAN THESE EVERYDAY KINDS OF PAIN DURING THE LAST WEEK? - SELECTED CHOICE | BPI.1.","THROUGHOUT OUR LIVES, MOST OF US HAVE HAD PAIN FROM TIME TO TIME\n(SUCH AS MINOR HEADACHES, SPRAINS, AND TOOTHACHES). HAVE YOU HAD\nPAIN OTHER THAN THESE EVERYDAY KINDS OF PAIN DURING THE LAST WEEK? - YES (PLEASE SPECIFY) - TEXT | BPI.1._1_TEXT",DID YOU TAKE PAIN MEDICATIONS IN THE LAST 7 DAYS? | BPI.1A.,I FEEL I HAVE HAD SOME PAIN THAT REQUIRES MEDICATION EACH AND EVERY DAY | BPI.1B.,PLEASE RATE YOUR PAIN ACCORDING TO THE FOLLOWING STATEMENTS: - PLEASE RATE YOUR PAIN BY FILLING IN THE ONE NUMBER THAT BEST DESCRIBES YOUR PAIN AT ITS WORST IN THE PAST 24 HOURS. | BPI.3._1,PLEASE RATE YOUR PAIN ACCORDING TO THE FOLLOWING STATEMENTS: - PLEASE RATE YOUR PAIN BY FILLING IN THE ONE NUMBER THAT BEST DESCRIBES YOUR PAIN AT ITS LEAST IN THE PAST 24 HOURS | BPI.3._2,PLEASE RATE YOUR PAIN ACCORDING TO THE FOLLOWING STATEMENTS: - PLEASE RATE YOUR PAIN BY FILLING IN THE ONE NUMBER THAT BEST DESCRIBES YOUR PAIN ON THE AVERAGE. | BPI.3._3,WHAT TREATMENTS OR MEDICATIONS ARE YOU RECEIVING FOR YOUR PAIN? | BPI.4.,"IN THE PAST 24 HOURS, HOW MUCH RELIEF HAVE PAIN TREATMENTS OR \nMEDICATIONS PROVIDED? PLEASE SELECT THE ONE PERCENTAGE THAT MOST\nSHOWS HOW MUCH RELIEF YOU HAVE RECEIVED. | BPI.5.","SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - GENERAL ACTIVITY | BPI.6._1","SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - MOOD | BPI.6._2","SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - WALKING ABILITY | BPI.6._3","SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - NORMAL WORK (INCLUDES BOTH WORK OUTSIDE THE HOME AND HOUSEWORK) | BPI.6._4","SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - RELATION WITH OTHER PEOPLE | BPI.6._5","SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - SLEEP | BPI.6._6","SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - ENJOYMENT OF LIFE | BPI.6._7",Phase,1.\tPLEASE BRIEFLY DESCRIBE YOUR EXPERIENCE IN THE KAMBO RITUAL: | QUAL.1.,2. WERE THERE SPECIFIC ASPECTS OF THE RITUAL THAT WERE PARTICULARLY VALUABLE? | QUAL.2.,3.\tWERE THERE SPECIFIC ASPECTS OF THE RITUAL THAT WERE PARTICULARLY CHALLENGING? | QUAL.3.,DID YOU EXPERIENCE ANY EMOTIONAL ELEMENTS OF THE KAMBO RITUAL? | QUAL.4.,5.\tDID YOU EXPERIENCE ANY SPIRITUAL ELEMENTS OF THE KAMBO RITUAL? | QUAL.5.,6.\tWHAT WERE THE REASONS YOU SOUGHT OUT KAMBO AND DID THE PROCESS SATISFY THEM? | QUAL 6.,"ON THE FOLLOWING PAGES YOU WILL FIND A NUMBER OF STATEMENTS AND BELOW EACH \nSTATEMENT A LINE WITH THE ENDPOINTS “NO, NOT MORE THAN USUALLY” AND “YES, MUCH MORE \nTHAN USUALLY.” THE LINE REPRESENTS SOMETHING LIKE A THERMOMETER THAT WILL BE USED TO \nASSESS ALTERATIONS FROM YOUR NORMAL WAKING CONSCIOUSNESS.\n\n\nPLEASE RATE TO WHAT EXTENT THE STATEMENTS APPLY TO YOUR PARTICULAR EXPERIENCE –\nCOMPARED TO NORMAL WAKING CONSCIOUSNESS – BY USING THE SLIDER ON THE LINE \nNEXT TO THE STATEMENTS.\n\n\nPLEASE NOTE THAT YOUR NORMAL WAKING CONSCIOUSNESS CORRESPONDS TO A MARK AT THE \nVERY LEFT END OF THE SCALE, I.E.: “NO, NOT MORE THAN USUALLY.” | INSTRUCTIONS","1.\tHAVE ANY OF THE PHYSICAL, EMOTIONAL OR SPIRITUAL EFFECTS FROM THE KAMBO PROCESS PERSISTED UNTIL THIS POINT? | QUAL.1.",3.\tDO YOU FEEL THAT THERE ARE ANY LASTING CHANGES FROM HAVING DONE KAMBO? | QUAL.3.,4. DID KAMBO HAVE ANY IMPACT ON YOUR LIFE? PLEASE DESCRIBE. | QUAL.4.,5.\tDO YOU HAVE THE INTENTION TO DO KAMBO AGAIN AT SOME POINT IN YOUR LIFE? WHY OR WHY NOT? | QUAL.5.,6.\tIS THERE ANYTHING ELSE YOU'D LIKE TO SHARE WITH US? | QUAL 6.,non_null_count,practitioner,scheduled session 1,scheduled session 3,Days btwn,Health diagnosis,Autoimmu,Meds,Session 1,# of points,location of points,Private or group,vomit,BM,Fainting,Rapeh,Sananga,Session 2,# of points.1,location of points.1,Private or group.1,vomit.1,BM.1,Fainting.1,Rapeh.1,Sananga.1,Session 3,# of points.2,location of points.2,Private or group.2,vomit.2,BM.2,Fainting.2,Rapeh.2,Sananga.2,Private_or_group_numeric,AnonID,MEQ30_Ineffability,MEQ30_MysticalExperience,MEQ30_PositiveMood,MEQ30_TranscendenceOfTimeAndSpace,MEQ30_TotalScore,CEQ30_Isolation_SUM,CEQ30_Fear_SUM,CEQ30_Grief_SUM,CEQ30_Insanity_SUM,CEQ30_Death_SUM,CEQ30_Paranoia_SUM,CEQ30_PhysicalDistress_SUM,CEQ30_Total_SUM,5DASC_OceanicBoundlessness_Score,5DASC_AnxiousEgoDissolution_Score,5DASC_VisionaryRestructuralization_Score,5DASC_AuditoryAlterations_Score,5DASC_ReductionOfVigilance_Score,5DASC_TotalScore,MAAS_Total,RYFF_Total,RYFF_Autonomy_Score,RYFF_EnvironmentalMastery_Score,RYFF_PersonalGrowth_Score,RYFF_PositiveRelations_Score,RYFF_PurposeInLife_Score,RYFF_SelfAcceptance_Score,MFI_General_Fatigue_Score,MFI_Physical_Fatigue_Score,MFI_Reduced_Activity_Score,MFI_Reduced_Motivation_Score,MFI_Mental_Fatigue_Score,MFI_TotalScore,IDS_TotalScore,SHS_TotalScore
0,0,2023-02-16 20:16:10,2023-02-16 21:05:37,IP Address,76.181.171.194,100,2966,True,2023-02-16 21:05:38,R_stm7DF0q0ZkFcoF,NaN,NaN,NaN,NaN,41.2463,-81.8310,anonymous,EN,Kevin Sheard,2/17/23,3/17/23,28.0,Female,Cis-Female,NaN,Other,"University (e.g., bachelor’s degree)","$25,000-$50,000 annually",5’3”,119,Multiple Sclerosis. Mostly recovered. Only dea...,No,No,Vit D/ fish oil/ brown seaweed,Yes,Often,I heard it could be beneficial for those with ...,6,Extremely excited,Yes (please specify),Intermittent back pain,No,No,4,0 - No Pain,3,Red light therapy/ icy hot,90%,0 - Does not interfere,3,0 - Does not interfere,4,2,0 - Does not interfere,0 - Does not interfere,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,162,Kevin sheard,2/17,3/17,28.0,Multiple Sclerosis,x,NaN,NaN,3.0,upper arm,private,1,0.0,N,Y,Y,NaN,3.0,chest,private,Y,N,N,Y,Y,NaN,3,2 chest 1 neck,private,Y,N,N,Y,Y,0,P001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.400000,4.976190,5.428571,4.857143,5.857143,4.571429,4.000000,5.142857,2.25,4.25,4.25,4.00,3.00,3.55,18.0,4.50
1,1,3/22/2023 10:03,3/22/2023 11:26,IP Address,76.188.214.194,100,4965,True,3/22/2023 11:26,R_3CCuL24AWuFvoqH,NaN,NaN,NaN,NaN,41.4481,-82.0177,anonymous,EN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,My experience in the ritual was more miles tha...,The music Kevin played alleviated anxiety and ...,The sananga and hapé were more challenging tha...,"Yes, the second session started emotionally be...","Yes! After doing Kambò I started, noticing my ...",I have always had an interest in any natural m...,NaN,NaN,NaN,NaN,NaN,NaN,322,Kevin sheard,2/17,3/17,28.0,Multiple Sclerosis,x,NaN,NaN,3.0,upper arm,private,1,0.0,N,Y,Y,NaN,3.0,chest,private,Y,N,N,Y,Y,NaN,3,2 chest 1 neck,private,Y,N,N,Y,Y,0,P001,0.666667,1.466667,1.500000,0.666667,1.075000,0.0,0.25,0.4,0.0,0.0,0.0,1.333333,0.283333,70.6,0.000,54.833333,10.833333,20.00,31.253333,3.200000,5.536585,6.000000,6.000000,6.166667,4.857143,4.571429,5.714286,2.50,4.50,4.50,4.25,3.25,3.80,13.0,5.00
2,2,6/19/2023 13:37,6/19/2023 14:40,IP Address,76.188.214.194,100,3747,True,6/19/2023 14:40,R_PwEw1U2O3Uapejn,NaN,NaN,NaN,NaN,41.4481,-82.0177,anonymous,EN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,"Yes, cutting sugar and alcohol. I no longer dr...",NaN,NaN,NaN,NaN,NaN,"Yes, I haven’t gotten sick once since my first...","Yes, a lot. To name a few: \nNoticing my thoug...","Absolutely, I was facing Chemotherapy and stea...",I self serve and am very interested in becomin...,I teared up taking this survey. I cannot put i...,135,Kevin sheard,2/17,3/17,28.0,Multiple Sclerosis,x,NaN,NaN,3.0,upper arm,private,1,0.0,N,Y,Y,NaN,3.0,chest,private,Y,N,N,Y,Y,NaN,3,2 chest 1 neck,private,Y,N,N,Y,Y,0,P001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.466667,4.904762,5.857143,5.285714,5.285714,5.000000,4.000000,4.000000,3.50,4.00,3.75,4.25,3.50,3.80,11.0,5.25
3,3,2023-02-16 20:01:21,2023-02-17 12:55:01,IP Address,174.216.50.49,100,60820,True,2023-02-17 12:55:02,R_UsXoVyTDkjEeRPz,NaN,NaN,NaN,NaN,39.9458,-74.9042,anonymous,EN,Nicole O’Malley,2/17/2023,3/4 or 3/11 we have not worked out the date yet,45.0,Female,Cis-Female,NaN,"Caucasian / White (e.g., German, Irish, Englis...",High school,"$50,000-$75,000 annually","5'3""",185,Alopecia areata that has developed into alopec...,No,No,"Levocetirizine 5mg, Montelukast 10mg, Symbicor...",Yes,Daily,"My autoimmune, Alopecia, but have wanted to si...",6,8,No,NaN,No,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,149,Nikki O malley,2/17,March 18,29.0,"alopecia universalis, previous breast cancer",x,"Levocetirizine, Prilosec, Albuterol as needed",NaN,5.0,"chakra- 1 throat, 2 heart, 2 solar",group,1,1.0,N,Y,Y,NaN,7.0,upper arm,group,Y,Y,N,Y,Y,NaN,8,auricular,group,Y,N,N,Y,Y,2,P002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.600000,3.976190,2.714286,2.857143,3.714286,5.000000,5.428571,4.142857,1.75,1.75,1.50,2.25,2.00,1.85,39.0,2.00
4,4,3/24/2023 8:08,3/24/2023 14:08,IP Address,104.129.205.6,100,21572,True,3/24/2023 14:08,R_2RXuEgPN1tbY4T6,NaN,NaN,NaN,NaN,35.2296,-80.8430,anonymous,EN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,Yes,No,1,0 - No Pain,1,Advil for minor headaches,100% - Complete Relief,0 - Does not interfere,2,0 - Does not interfere,0 - Does not interfere,0 - Does not interfere,1,1,2,"The experience was intense, but also amazing w...",I think being introduced to Rapé. I will seek...,I felt that my first session was the easiest a...,Yes. I felt it brought up many emotions.,I think every Kambo ritual is a spiritual expe...,I meet Nikki new years eve 2019/2020 and have ...,NaN,NaN,NaN,NaN,NaN,NaN,330,Nikki O malley,2/17,March 18,29.0,"alopecia universalis, previous breast cancer",x,"Levocetirizine, Prilosec, Albuterol as needed",NaN,5.0,"chakra- 1 throat, 2 heart, 2 solar",group,1,1.0,N,Y,Y,NaN,7.0,upper arm,group,Y,Y,N,Y,Y,NaN,8,auricular,group,Y,N,N,Y,Y,2,P002,2.333333,1.066667,2.333333,0.500000,1.558333,0.0,0.60,0.6,0.0,0.0,0.0,1.500000,0.385714,19.5,1.875,1.600000,0.000000,21.25,8.845000,3.066667,4.238095,4.000000,3.571429,4.428571,4.285714,4.714286,4.428571,2.75,1.25,2.50,2.75,2.75,2.40,22.0,2.75

In [15]:
import pandas as pd
import numpy as np

# Copy base dataframe for processing (replace with your actual base DataFrame as needed)
df_bpi_scored = df_shs_cleaned.copy()  # or df_bpi_raw if available

# Generic mapping for BPI responses (robust for most real-world cases)
bpi_map = {
    '0 - No Pain': 0, '0': 0, '0% - No Relief': 0, '100% - Complete Relief': 100,
    '0 - Does not interfere': 0, '1': 1, '2': 2, '3': 3, '4': 4, '5': 5,
    '6': 6, '7': 7, '8': 8, '9': 9, '10': 10, '10 - Completely interferes': 10,
    'Not answered': np.nan, 'N/A': np.nan, 'NA': np.nan, 'nan': np.nan,
    '': np.nan, 'None': np.nan
}

# Step 1: Clean pain severity responses (BPI.3._1 to BPI.3._3)
severity_cols = [
    'PLEASE RATE YOUR PAIN ACCORDING TO THE FOLLOWING STATEMENTS: - PLEASE RATE YOUR PAIN BY FILLING IN THE ONE NUMBER THAT BEST DESCRIBES YOUR PAIN AT ITS WORST IN THE PAST 24 HOURS. | BPI.3._1',
    'PLEASE RATE YOUR PAIN ACCORDING TO THE FOLLOWING STATEMENTS: - PLEASE RATE YOUR PAIN BY FILLING IN THE ONE NUMBER THAT BEST DESCRIBES YOUR PAIN AT ITS LEAST IN THE PAST 24 HOURS | BPI.3._2',
    'PLEASE RATE YOUR PAIN ACCORDING TO THE FOLLOWING STATEMENTS: - PLEASE RATE YOUR PAIN BY FILLING IN THE ONE NUMBER THAT BEST DESCRIBES YOUR PAIN ON THE AVERAGE. | BPI.3._3',
]

print("\n--- Unique values for Severity columns (after mapping, before numeric conversion) ---")
for col in severity_cols:
    # Apply mapping
    df_bpi_scored[col] = df_bpi_scored[col].map(bpi_map).where(df_bpi_scored[col].map(bpi_map).notna(), df_bpi_scored[col])
    # Print unique values after mapping
    print(f"\n{col}:\n", df_bpi_scored[col].unique())
    # Extract numbers (allow decimal) and convert
    df_bpi_scored[col] = (
        df_bpi_scored[col]
        .astype(str)
        .str.extract(r"(\d{1,2}(?:\.\d)?)")[0]
        .astype(float)
    )

# 30% rule: at least 2 of 3 items present
valid_severity = df_bpi_scored[severity_cols].notna().sum(axis=1) >= 2
df_bpi_scored['BPI_PainSeverityIndex'] = df_bpi_scored[severity_cols].mean(axis=1).where(valid_severity)

# Step 2: Clean pain interference responses (BPI.6._1 to BPI.6._7)
interference_cols = [
    'SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - GENERAL ACTIVITY | BPI.6._1',
    'SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - MOOD | BPI.6._2',
    'SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - WALKING ABILITY | BPI.6._3',
    'SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - NORMAL WORK (INCLUDES BOTH WORK OUTSIDE THE HOME AND HOUSEWORK) | BPI.6._4',
    'SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - RELATION WITH OTHER PEOPLE | BPI.6._5',
    'SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - SLEEP | BPI.6._6',
    'SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - ENJOYMENT OF LIFE | BPI.6._7',
]

print("\n--- Unique values for Interference columns (after mapping, before numeric conversion) ---")
for col in interference_cols:
    df_bpi_scored[col] = df_bpi_scored[col].map(bpi_map).where(df_bpi_scored[col].map(bpi_map).notna(), df_bpi_scored[col])
    print(f"\n{col}:\n", df_bpi_scored[col].unique())
    df_bpi_scored[col] = (
        df_bpi_scored[col]
        .astype(str)
        .str.extract(r"(\d{1,2}(?:\.\d)?)")[0]
        .astype(float)
    )

# 30% rule: at least 5 of 7 items present
valid_interference = df_bpi_scored[interference_cols].notna().sum(axis=1) >= 5
df_bpi_scored['BPI_PainInterferenceIndex'] = df_bpi_scored[interference_cols].mean(axis=1).where(valid_interference)

# Step 3: Clean relief percentage (BPI.5)
relief_col = 'IN THE PAST 24 HOURS, HOW MUCH RELIEF HAVE PAIN TREATMENTS OR \nMEDICATIONS PROVIDED? PLEASE SELECT THE ONE PERCENTAGE THAT MOST\nSHOWS HOW MUCH RELIEF YOU HAVE RECEIVED. | BPI.5.'
print("\n--- Unique values for Relief column (after mapping, before numeric conversion) ---")
df_bpi_scored[relief_col] = df_bpi_scored[relief_col].map(bpi_map).where(df_bpi_scored[relief_col].map(bpi_map).notna(), df_bpi_scored[relief_col])
print(f"\n{relief_col}:\n", df_bpi_scored[relief_col].unique())
df_bpi_scored['BPI_PainReliefPercent'] = (
    df_bpi_scored[relief_col]
    .astype(str)
    .str.extract(r"(\d{1,3}(?:\.\d)?)")[0]
    .astype(float)
    .clip(0, 100)
)

# Step 4: Drop raw scoring columns
drop_cols = severity_cols + interference_cols + [relief_col]
df_bpi_cleaned = df_bpi_scored.drop(columns=drop_cols, errors='ignore')

# Step 5: Export
df_bpi_cleaned.to_csv("Kambo_with_BPI_scored.csv", index=False)

print("\n--- Final BPI scored columns (first five rows): ---")
print(df_bpi_cleaned[['BPI_PainSeverityIndex', 'BPI_PainInterferenceIndex', 'BPI_PainReliefPercent']].head())

--- Unique values for Severity columns (after mapping, before numeric conversion) ---

PLEASE RATE YOUR PAIN ACCORDING TO THE FOLLOWING STATEMENTS: - PLEASE RATE YOUR PAIN BY FILLING IN THE ONE NUMBER THAT BEST DESCRIBES YOUR PAIN AT ITS WORST IN THE PAST 24 HOURS. | BPI.3._1:
 [4.0 nan 1.0 2.0 5.0 6.0 8.0 3.0 7.0 0.0 9.0]

PLEASE RATE YOUR PAIN ACCORDING TO THE FOLLOWING STATEMENTS: - PLEASE RATE YOUR PAIN BY FILLING IN THE ONE NUMBER THAT BEST DESCRIBES YOUR PAIN AT ITS LEAST IN THE PAST 24 HOURS | BPI.3._2:
 [0.0 nan 1.0 2.0 3.0 5.0 6.0 4.0 7.0]

PLEASE RATE YOUR PAIN ACCORDING TO THE FOLLOWING STATEMENTS: - PLEASE RATE YOUR PAIN BY FILLING IN THE ONE NUMBER THAT BEST DESCRIBES YOUR PAIN ON THE AVERAGE. | BPI.3._3:
 [3.0 nan 1.0 7.0 6.0 5.0 2.0 4.0 0.0]

--- Unique values for Interference columns (after mapping, before numeric conversion) ---

SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - GENERAL ACTIVITY | BPI.6._1:
 [0.0 nan 4.0 3.0 5.0 7.0 6.0 2.0 1.0 8.0]

SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - MOOD | BPI.6._2:
 [3.0 nan 2.0 8.0 6.0 5.0 4.0 0.0 7.0 1.0 10.0]

SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - WALKING ABILITY | BPI.6._3:
 [0.0 nan 6.0 3.0 8.0 1.0 2.0 7.0 4.0 10.0 5.0]

SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - NORMAL WORK (INCLUDES BOTH WORK OUTSIDE THE HOME AND HOUSEWORK) | BPI.6._4:
 [4.0 nan 0.0 8.0 5.0 2.0 3.0 1.0 7.0 6.0 10.0]

SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - RELATION WITH OTHER PEOPLE | BPI.6._5:
 [2.0 nan 0.0 5.0 6.0 3.0 4.0 1.0 7.0 10.0 8.0]

SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - SLEEP | BPI.6._6:
 [0.0 nan 1.0 7.0 9.0 8.0 2.0 4.0 5.0 3.0 6.0 10.0]

SELECT THE NUMBER THAT DESCRIBES HOW, DURING THE PAST 24 HOURS, PAIN HAS INTERFERED WITH YOUR: - ENJOYMENT OF LIFE | BPI.6._7:
 [0.0 nan 1.0 2.0 9.0 5.0 7.0 3.0 6.0 4.0 8.0 10.0]

--- Unique values for Relief column (after mapping, before numeric conversion) ---

IN THE PAST 24 HOURS, HOW MUCH RELIEF HAVE PAIN TREATMENTS OR
MEDICATIONS PROVIDED? PLEASE SELECT THE ONE PERCENTAGE THAT MOST
SHOWS HOW MUCH RELIEF YOU HAVE RECEIVED. | BPI.5.:
 ['90%' nan 100.0 '80%' '40%' '50%' '60%' '70%' 0.0 '30%' '10%' '20%']

--- Final BPI scored columns (first five rows): ---
   BPI_PainSeverityIndex  BPI_PainInterferenceIndex  BPI_PainReliefPercent
0               2.333333                   1.285714                   90.0
1                    NaN                        NaN                    NaN
2                    NaN                        NaN                    NaN
3                    NaN                        NaN                    NaN
4               0.666667                   0.571429                  100.0

In [16]:
import re
from collections import defaultdict

# Reload the session dataset
df_session = df_bpi_cleaned.copy()

# Define point and location columns
location_columns = ['location of points', 'location of points.1', 'location of points.2']
point_columns = ['# of points', '# of points.1', '# of points.2']

# Updated keyword-region mapping
region_keywords = {
    "head": [
        "ear", "ears", "auricular", "shen men", "point zero", "cerebral",
        "master oscillation", "thalamus", "forehead", "face"
    ],
    "neck": ["neck", "throat"],
    "thorax": [
        "chest", "sternum", "heart", "lung", "heart chakra",
        "back", "upper back", "center back", "mid spine", "upper spine"
    ],
    "abdomen": [
        "abdomen", "solar plexus", "mid back", "front of chest",
        "stomach", "solar"
    ],
    "pelvis": [
        "sacrum", "sacral", "pelvis", "root", "lower back", "low back",
        "root chakra", "lower spine"
    ],
    "upper_extremity": [
        "shoulder", "arm", "upper arm", "l arm", "r arm", "left arm",
        "right arm", "hand", "elbow", "wrist"
    ],
    "lower_extremity": [
        "leg", "ankle", "knee", "lower leg", "foot", "feet", "toe"
    ]
}

# Reverse mapping for keyword search
keyword_to_region = {}
for region, keywords in region_keywords.items():
    for kw in keywords:
        keyword_to_region[kw] = region

# Function to parse locations
def parse_location_string(text):
    point_map = defaultdict(int)
    text = str(text).lower().strip()
    matches = re.findall(r'(\d+)\s+(?:on\s+)?([\w\s\-]+)', text)
    for num_str, body_part in matches:
        num = int(num_str)
        for kw, region in keyword_to_region.items():
            if re.search(rf"\b{re.escape(kw)}\b", body_part):
                point_map[region] += num
                break
        else:
            point_map["unclassified"] += num
    return point_map

# List of regions
regions = list(region_keywords.keys())

# Initialize per-session region columns
for session in [1, 2, 3]:
    for region in regions:
        df_session[f'Session{session}_{region}'] = 0

# Apply region classification per session
for idx, row in df_session.iterrows():
    for session_idx, (loc_col, pts_col) in enumerate(zip(location_columns, point_columns), start=1):
        text = str(row.get(loc_col, '')).strip().lower()
        parsed = parse_location_string(text)
        for region in regions:
            df_session.at[idx, f'Session{session_idx}_{region}'] += parsed.get(region, 0)

# Drop original raw location and point columns
df_session_cleaned = df_session.drop(columns=location_columns + point_columns, errors='ignore')

# Export cleaned dataframe
df_session_cleaned.to_csv("Kambo_session_regions_scored.csv", index=False)

In [17]:
# Redefine binary and private/group columns with correct capitalization
private_cols = ['Private or group', 'Private or group.1', 'Private or group.2']
binary_columns = {
    'Vomit': ['vomit', 'vomit.1', 'vomit.2'],
    'BM': ['BM', 'BM.1', 'BM.2'],
    'Fainting': ['Fainting', 'Fainting.1', 'Fainting.2'],
    'Rapeh': ['Rapeh', 'Rapeh.1', 'Rapeh.2'],
    'Sananga': ['Sananga', 'Sananga.1', 'Sananga.2']
}

df_standardized = df_session_cleaned.copy()
standardized_private = {}
standardized_binary = {}

# Standardize private/group
for i, col in enumerate(private_cols, start=1):
    new_col = f'Private_or_group_{i}_NUM'
    standardized_private[new_col] = (
        df_session[col]
        .astype(str)
        .str.strip()
        .str.lower()
        .replace({
            'private': 1, 'p': 1, 'alone': 1,
            'group': 0, 'group of 2': 0, 'semi private': 0, 'semi': 0, 'g (2 people)': 0,
            'public': 0, '0': 0, '1': 1
        })
        .apply(lambda x: pd.to_numeric(x, errors='coerce'))
    )

# Standardize binary Y/N fields
for label, cols in binary_columns.items():
    for i, col in enumerate(cols, start=1):
        new_col = f'{label}_{i}_NUM'
        standardized_binary[new_col] = (
            df_session[col]
            .astype(str)
            .str.strip()
            .str.lower()
            .replace({
                'yes': 1, 'y': 1, '1': 1,
                'no': 0, 'n': 0, '0': 0
            })
            .apply(lambda x: pd.to_numeric(x, errors='coerce'))
        )

# Merge all new numeric columns
for col_name, series in {**standardized_private, **standardized_binary}.items():
    df_standardized[col_name] = series

# Drop original columns
cols_to_drop = private_cols + [col for sublist in binary_columns.values() for col in sublist]
df_standardized = df_standardized.drop(columns=cols_to_drop, errors='ignore')

# Export
df_standardized.to_csv("Kambo_session_all_standardized.csv", index=False)

In [18]:
df_demo = df_standardized.copy()

# ------------------------
# Helper: convert height to inches
# ------------------------
def parse_height(height):
    if pd.isna(height):
        return np.nan

    height = str(height).lower().strip().replace("’", "'").replace("”", '"')
    height = re.sub(r'[^a-z0-9\'\"\s.]', '', height)

    # Handle spelled-out cases
    if height in ['six', '6']:
        return 72
    if height in ['five', '5']:
        return 60

    # Handle common patterns
    match_ft_in = re.search(r'(\d)\s*ft[\s\.]*(\d{1,2})?', height)
    if match_ft_in:
        ft = int(match_ft_in.group(1))
        inches = int(match_ft_in.group(2)) if match_ft_in.group(2) else 0
        return ft * 12 + inches

    match_ft_sym = re.search(r"(\d)'\s*(\d{1,2})?", height)
    if match_ft_sym:
        ft = int(match_ft_sym.group(1))
        inches = int(match_ft_sym.group(2)) if match_ft_sym.group(2) else 0
        return ft * 12 + inches

    match_dec = re.match(r'(\d+)[.,](\d+)', height)
    if match_dec:
        try:
            return round(float(height) * 12)
        except:
            return np.nan

    return np.nan

# ------------------------
# Helper: convert weight to lbs
# ------------------------
def parse_weight(weight):
    if pd.isna(weight):
        return np.nan
    weight = str(weight).lower().replace('lbs', '').replace('lb', '').strip()
    try:
        val = float(re.findall(r'\d+', weight)[0])
        return val if 80 <= val <= 400 else np.nan
    except:
        return np.nan

# ------------------------
# Helper: scale mappings
# ------------------------
edu_map = {
    'high school': 1,
    'college diploma or technical/trade school': 2,
    'university (e.g., bachelor’s degree)': 3,
    'professional degree (e.g., md, pharmd, llb, jd)': 4,
    'post-graduate degree (e.g., master’s or phd)': 5
}

income_map = {
    'less than $24,999 annually': 1,
    '$25,000-$50,000 annually': 2,
    '$50,000-$75,000 annually': 3,
    '$75,000-$100,000 annually': 4,
    '$100,000-$125,000 annually': 5,
    '$125,000-$150,000 annually': 6,
    'more than $150,000 annually': 7
}

binary_map = {'yes': 1, 'no': 0}
cannabis_map = {'never': 0, 'rarely': 1, 'often': 2, 'daily': 3}
gender_map = {'cis-female': 0, 'cis-male': 1, 'other': 2}
sex_map = {'female': 0, 'male': 1}
nervous_map = {'not nervous at all': 0, 'extremely nervous': 8}
excited_map = {'extremely excited': 8}

# ------------------------
# Standardization Logic
# ------------------------
df_standardized['Age'] = pd.to_numeric(df_demo["WHAT IS YOUR AGE? | DEMO.1."], errors='coerce')
df_standardized['Sex'] = df_demo["WHAT BIOLOGICAL SEX WERE YOU ASSIGNED AT BIRTH? | DEMO.2."].str.lower().map(sex_map)
df_standardized['Gender'] = df_demo["WHAT GENDER DO YOU IDENTIFY WITH? - SELECTED CHOICE | DEMO.3."].str.lower().map(gender_map)
df_standardized['Education'] = df_demo["WHAT IS YOUR HIGHEST LEVEL OF EDUCATION COMPLETED? | DEMO.5."].str.lower().map(edu_map)
df_standardized['Income'] = df_demo["WHAT IS YOUR GROSS HOUSEHOLD INCOME? | DEMO.6."].str.lower().map(income_map)
df_standardized['Height_in'] = df_demo["WHAT IS YOUR APPROXIMATE HEIGHT (FT, IN)? | DEMO.7."].apply(parse_height)
df_standardized['Weight_lb'] = df_demo["WHAT IS YOUR APPROXIMATE WEIGHT (LBS)? | DEMO.8."].apply(parse_weight)
df_standardized['Lyme_DX'] = df_demo["HAVE YOU BEEN DIAGNOSED WITH LYME DISEASE BY A LICENSED HEALTHCARE PROFESSIONAL? | DEMO.10."].str.lower().map(binary_map)
df_standardized['Post_Lyme_DX'] = df_demo["HAVE YOU BEEN DIAGNOSED WITH POST-TREATMENT LYME SYNDROME BY A LICENSED HEALTHCARE PROFESSIONAL? | DEMO.11."].str.lower().map(binary_map)
df_standardized['Psychedelic_Use'] = df_demo["HAVE YOU EVER USED A PSYCHEDELIC SUBSTANCE SUCH AS LSD, PSILOCYBIN (MAGIC) MUSHROOMS, MESCALINE (PEYOTE), DMT, OR AYAHUASCA? | DEMO.13."].str.lower().map(binary_map)
df_standardized['Cannabis_Use'] = df_demo["DO YOU USE CANNABIS? | DEMO.14."].str.lower().map(cannabis_map)

# Nervousness and excitement
df_standardized['Nervous'] = df_demo["PLEASE SELECT THE OPTION THAT REFLECTS HOW NERVOUS YOU ARE FEELING ABOUT YOUR UPCOMING KAMBO EXPERIENCES. | DEMO.16."].str.lower().replace(nervous_map).apply(pd.to_numeric, errors='coerce')
df_standardized['Excited'] = df_demo["PLEASE SELECT THE OPTION THAT REFLECTS HOW EXCITED YOU ARE FEELING ABOUT YOUR UPCOMING KAMBO EXPERIENCES. | DEMO.17."].str.lower().replace(excited_map).apply(pd.to_numeric, errors='coerce')

# BMI
height_m = df_standardized['Height_in'] * 0.0254
weight_kg = df_standardized['Weight_lb'] * 0.453592
df_standardized['BMI'] = weight_kg / (height_m ** 2)

columns_to_drop = [
    "WHAT IS YOUR AGE? | DEMO.1.",
    "WHAT BIOLOGICAL SEX WERE YOU ASSIGNED AT BIRTH? | DEMO.2.",
    "WHAT GENDER DO YOU IDENTIFY WITH? - SELECTED CHOICE | DEMO.3.",
    "WHAT RACE DO YOU IDENTIFY AS? | DEMO.4.",
    "WHAT IS YOUR HIGHEST LEVEL OF EDUCATION COMPLETED? | DEMO.5.",
    "WHAT IS YOUR GROSS HOUSEHOLD INCOME? | DEMO.6.",
    "WHAT IS YOUR APPROXIMATE HEIGHT (FT, IN)? | DEMO.7.",
    "WHAT IS YOUR APPROXIMATE WEIGHT (LBS)? | DEMO.8.",
    "HAVE YOU BEEN DIAGNOSED WITH LYME DISEASE BY A LICENSED HEALTHCARE PROFESSIONAL? | DEMO.10.",
    "HAVE YOU BEEN DIAGNOSED WITH POST-TREATMENT LYME SYNDROME BY A LICENSED HEALTHCARE PROFESSIONAL? | DEMO.11.",
    "HAVE YOU EVER USED A PSYCHEDELIC SUBSTANCE SUCH AS LSD, PSILOCYBIN (MAGIC) MUSHROOMS, MESCALINE (PEYOTE), DMT, OR AYAHUASCA? | DEMO.13.",
    "DO YOU USE CANNABIS? | DEMO.14.",
    "PLEASE SELECT THE OPTION THAT REFLECTS HOW NERVOUS YOU ARE FEELING ABOUT YOUR UPCOMING KAMBO EXPERIENCES. | DEMO.16.",
    "PLEASE SELECT THE OPTION THAT REFLECTS HOW EXCITED YOU ARE FEELING ABOUT YOUR UPCOMING KAMBO EXPERIENCES. | DEMO.17."
]

# Export final standardized demographics dataset
df_cleaned = df_standardized.drop(columns=columns_to_drop, errors='ignore')
df_cleaned.to_csv("Kambo_demo_standardized.csv", index=False)

In [19]:
df = df_cleaned.copy()

# List of demographic columns to propagate
columns_to_propagate = [
    "Age", "Sex", "Gender", "Education", "Income", "Height_in", "Weight_lb",
    "Lyme_DX", "Post_Lyme_DX", "Psychedelic_Use", "Cannabis_Use", "Nervous", "Excited", "BMI"
]

# Extract Phase 1 values for each AnonID
df_phase1 = df[df['Phase'] == 1][['AnonID'] + columns_to_propagate].drop_duplicates(subset='AnonID')

# Merge back into the original dataframe using AnonID
df_filled = df.drop(columns=columns_to_propagate).merge(df_phase1, on='AnonID', how='left')

# Export the final dataset
df_filled.to_csv("Kambo_phases_demographics_propagated_clean.csv", index=False)

In [20]:
df = df_filled.copy()

# Drop the listed columns
columns_to_drop = [
    'START DATE | STARTDATE', 'END DATE | ENDDATE', 'RESPONSE TYPE | STATUS', 'IP ADDRESS | IPADDRESS',
    'PROGRESS', 'DURATION (IN SECONDS)', 'FINISHED', 'RECORDED DATE | RECORDEDDATE', 'RESPONSE ID | RESPONSEID',
    'RECIPIENT LAST NAME | RECIPIENTLASTNAME', 'RECIPIENT FIRST NAME | RECIPIENTFIRSTNAME',
    'RECIPIENT EMAIL | RECIPIENTEMAIL', 'EXTERNAL DATA REFERENCE | EXTERNALREFERENCE',
    'LOCATION LATITUDE | LOCATIONLATITUDE', 'LOCATION LONGITUDE | LOCATIONLONGITUDE',
    'DISTRIBUTION CHANNEL | DISTRIBUTIONCHANNEL', 'USER LANGUAGE | USERLANGUAGE',
    'WHAT IS THE NAME OF THE PRACTITIONER YOU WILL BE WORKING WITH? | GEN.1.',
    'WHAT IS THE DATE OF YOUR 1ST SCHEDULED KAMBO SESSION? | GEN.2.',
    'WHAT IS THE DATE OF YOUR 3RD SCHEDULED KAMBO SESSION? | GEN.3.',
    'WHAT GENDER DO YOU IDENTIFY WITH? - OTHER - TEXT | DEMO.3._7_TEXT',
    'HAVE YOU BEEN DIAGNOSED WITH ANY MEDICAL CONDITIONS OR DISEASE? DO YOU CURRENTLY DEAL WITH THESE CONDITIONS OR HAVE YOU RECOVERED FROM THESE CONDITIONS? PLEASE EXPLAIN. | DEMO.9.',
    'PLEASE LIST ANY DRUGS, MEDICATIONS, OR SUPPLEMENTS YOU ARE CURRENTLY TAKING. | DEMO.12.',
    'WHAT ARE THE REASONS YOU HAVE SOUGHT OUT KAMBO? | DEMO.15.',
    'THROUGHOUT OUR LIVES, MOST OF US HAVE HAD PAIN FROM TIME TO TIME\n(SUCH AS MINOR HEADACHES, SPRAINS, AND TOOTHACHES). HAVE YOU HAD\nPAIN OTHER THAN THESE EVERYDAY KINDS OF PAIN DURING THE LAST WEEK? - SELECTED CHOICE | BPI.1.',
    'THROUGHOUT OUR LIVES, MOST OF US HAVE HAD PAIN FROM TIME TO TIME\n(SUCH AS MINOR HEADACHES, SPRAINS, AND TOOTHACHES). HAVE YOU HAD\nPAIN OTHER THAN THESE EVERYDAY KINDS OF PAIN DURING THE LAST WEEK? - YES (PLEASE SPECIFY) - TEXT | BPI.1._1_TEXT',
    'DID YOU TAKE PAIN MEDICATIONS IN THE LAST 7 DAYS? | BPI.1A.',
    'I FEEL I HAVE HAD SOME PAIN THAT REQUIRES MEDICATION EACH AND EVERY DAY | BPI.1B.',
    'WHAT TREATMENTS OR MEDICATIONS ARE YOU RECEIVING FOR YOUR PAIN? | BPI.4.',
    '1.	PLEASE BRIEFLY DESCRIBE YOUR EXPERIENCE IN THE KAMBO RITUAL: | QUAL.1.',
    '2. WERE THERE SPECIFIC ASPECTS OF THE RITUAL THAT WERE PARTICULARLY VALUABLE? | QUAL.2.',
    '3.	WERE THERE SPECIFIC ASPECTS OF THE RITUAL THAT WERE PARTICULARLY CHALLENGING? | QUAL.3.',
    'DID YOU EXPERIENCE ANY EMOTIONAL ELEMENTS OF THE KAMBO RITUAL? | QUAL.4.',
    '5.	DID YOU EXPERIENCE ANY SPIRITUAL ELEMENTS OF THE KAMBO RITUAL? | QUAL.5.',
    '6.	WHAT WERE THE REASONS YOU SOUGHT OUT KAMBO AND DID THE PROCESS SATISFY THEM? | QUAL 6.',
    'ON THE FOLLOWING PAGES YOU WILL FIND A NUMBER OF STATEMENTS AND BELOW EACH \nSTATEMENT A LINE WITH THE ENDPOINTS â€œNO, NOT MORE THAN USUALLYâ€ AND â€œYES, MUCH MORE \nTHAN USUALLY.â€ THE LINE REPRESENTS SOMETHING LIKE A THERMOMETER THAT WILL BE USED TO \nASSESS ALTERATIONS FROM YOUR NORMAL WAKING CONSCIOUSNESS.\n\n\nPLEASE RATE TO WHAT EXTENT THE STATEMENTS APPLY TO YOUR PARTICULAR EXPERIENCE â€“\nCOMPARED TO NORMAL WAKING CONSCIOUSNESS â€“ BY USING THE SLIDER ON THE LINE \nNEXT TO THE STATEMENTS.\n\n\nPLEASE NOTE THAT YOUR NORMAL WAKING CONSCIOUSNESS CORRESPONDS TO A MARK AT THE \nVERY LEFT END OF THE SCALE, I.E.: â€œNO, NOT MORE THAN USUALLY.â€ | INSTRUCTIONS',
    '1.	HAVE ANY OF THE PHYSICAL, EMOTIONAL OR SPIRITUAL EFFECTS FROM THE KAMBO PROCESS PERSISTED UNTIL THIS POINT? | QUAL.1.',
    '3.	DO YOU FEEL THAT THERE ARE ANY LASTING CHANGES FROM HAVING DONE KAMBO? | QUAL.3.',
    '4. DID KAMBO HAVE ANY IMPACT ON YOUR LIFE? PLEASE DESCRIBE. | QUAL.4.',
    '5.	DO YOU HAVE THE INTENTION TO DO KAMBO AGAIN AT SOME POINT IN YOUR LIFE? WHY OR WHY NOT? | QUAL.5.',
    "6.	IS THERE ANYTHING ELSE YOU'D LIKE TO SHARE WITH US? | QUAL 6.",
    'non_null_count', 'practitioner', 'scheduled session 1', 'scheduled session 3',
    'Health diagnosis', 'Meds', 'Session 1', 'Session 2', 'Session 3', 'Private_or_group_numeric']

# Drop the specified columns
df = df.drop(columns=columns_to_drop, errors='ignore')

df = df.loc[:, ~df.columns.str.startswith('ON THE FOLLOWING PAGES')]

# Convert 'Autoimmu' column: 'x' → 1, 0 → 0
df['Autoimmu'] = df['Autoimmu'].astype(str).str.lower().map({'x': 1, '0': 0})

# Export cleaned dataset
df.to_csv("Kambo_cleaned_final.csv", index=False)

In [21]:
# Identify CEQ30, MEQ30, and 5DASC subscale columns
scales_to_duplicate = [col for col in df.columns if any(scale in col for scale in ['CEQ30_', 'MEQ30_', '5DASC_'])]

# Extract Phase 2 values per AnonID
df_phase2_scales = df[df['Phase'] == 2][['AnonID'] + scales_to_duplicate].drop_duplicates(subset='AnonID')

# Merge into all rows using AnonID
df = df.drop(columns=scales_to_duplicate, errors='ignore').merge(
    df_phase2_scales,
    on='AnonID',
    how='left'
)

dasc_subscale_cols = [
    '5DASC_OceanicBoundlessness_Score',
    '5DASC_AnxiousEgoDissolution_Score',
    '5DASC_VisionaryRestructuralization_Score',
    '5DASC_AuditoryAlterations_Score',
    '5DASC_ReductionOfVigilance_Score'
]

# Extract Phase 2 values
df_phase2_dasc = df[df['Phase'] == 2][['AnonID'] + dasc_subscale_cols].drop_duplicates(subset='AnonID')

# Merge into all rows using AnonID
df_final = df.drop(columns=dasc_subscale_cols, errors='ignore').merge(
    df_phase2_dasc,
    on='AnonID',
    how='left'
)

# Export updated dataset
df_final.to_csv("Kambo_with_CEQ_MEQ_5DASC_duplicated.csv", index=False)

In [22]:
df_final.head()

,Unnamed: 0,Phase,Days btwn,Autoimmu,AnonID,MAAS_Total,RYFF_Total,RYFF_Autonomy_Score,RYFF_EnvironmentalMastery_Score,RYFF_PersonalGrowth_Score,RYFF_PositiveRelations_Score,RYFF_PurposeInLife_Score,RYFF_SelfAcceptance_Score,MFI_General_Fatigue_Score,MFI_Physical_Fatigue_Score,MFI_Reduced_Activity_Score,MFI_Reduced_Motivation_Score,MFI_Mental_Fatigue_Score,MFI_TotalScore,IDS_TotalScore,SHS_TotalScore,BPI_PainSeverityIndex,BPI_PainInterferenceIndex,BPI_PainReliefPercent,Session1_head,Session1_neck,Session1_thorax,Session1_abdomen,Session1_pelvis,Session1_upper_extremity,Session1_lower_extremity,Session2_head,Session2_neck,Session2_thorax,Session2_abdomen,Session2_pelvis,Session2_upper_extremity,Session2_lower_extremity,Session3_head,Session3_neck,Session3_thorax,Session3_abdomen,Session3_pelvis,Session3_upper_extremity,Session3_lower_extremity,Private_or_group_1_NUM,Private_or_group_2_NUM,Private_or_group_3_NUM,Vomit_1_NUM,Vomit_2_NUM,Vomit_3_NUM,BM_1_NUM,BM_2_NUM,BM_3_NUM,Fainting_1_NUM,Fainting_2_NUM,Fainting_3_NUM,Rapeh_1_NUM,Rapeh_2_NUM,Rapeh_3_NUM,Sananga_1_NUM,Sananga_2_NUM,Sananga_3_NUM,Age,Sex,Gender,Education,Income,Height_in,Weight_lb,Lyme_DX,Post_Lyme_DX,Psychedelic_Use,Cannabis_Use,Nervous,Excited,BMI,MEQ30_Ineffability,MEQ30_MysticalExperience,MEQ30_PositiveMood,MEQ30_TranscendenceOfTimeAndSpace,MEQ30_TotalScore,CEQ30_Isolation_SUM,CEQ30_Fear_SUM,CEQ30_Grief_SUM,CEQ30_Insanity_SUM,CEQ30_Death_SUM,CEQ30_Paranoia_SUM,CEQ30_PhysicalDistress_SUM,CEQ30_Total_SUM,5DASC_TotalScore,5DASC_OceanicBoundlessness_Score,5DASC_AnxiousEgoDissolution_Score,5DASC_VisionaryRestructuralization_Score,5DASC_AuditoryAlterations_Score,5DASC_ReductionOfVigilance_Score
0,0,1,28.0,1,P001,3.400000,4.976190,5.428571,4.857143,5.857143,4.571429,4.000000,5.142857,2.25,4.25,4.25,4.00,3.00,3.55,18.0,4.50,2.333333,1.285714,90.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,28.0,0.0,0.0,3.0,2.0,63.0,119.0,0.0,0.0,1.0,2.0,6.0,8.0,21.079670,0.666667,1.466667,1.500000,0.666667,1.075000,0.0,0.25,0.4,0.0,0.0,0.0,1.333333,0.283333,31.253333,70.6,0.000,54.833333,10.833333,20.00
1,1,2,28.0,1,P001,3.200000,5.536585,6.000000,6.000000,6.166667,4.857143,4.571429,5.714286,2.50,4.50,4.50,4.25,3.25,3.80,13.0,5.00,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,28.0,0.0,0.0,3.0,2.0,63.0,119.0,0.0,0.0,1.0,2.0,6.0,8.0,21.079670,0.666667,1.466667,1.500000,0.666667,1.075000,0.0,0.25,0.4,0.0,0.0,0.0,1.333333,0.283333,31.253333,70.6,0.000,54.833333,10.833333,20.00
2,2,3,28.0,1,P001,2.466667,4.904762,5.857143,5.285714,5.285714,5.000000,4.000000,4.000000,3.50,4.00,3.75,4.25,3.50,3.80,11.0,5.25,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,0,0,0,0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,28.0,0.0,0.0,3.0,2.0,63.0,119.0,0.0,0.0,1.0,2.0,6.0,8.0,21.079670,0.666667,1.466667,1.500000,0.666667,1.075000,0.0,0.25,0.4,0.0,0.0,0.0,1.333333,0.283333,31.253333,70.6,0.000,54.833333,10.833333,20.00
3,3,1,29.0,1,P002,3.600000,3.976190,2.714286,2.857143,3.714286,5.000000,5.428571,4.142857,1.75,1.75,1.50,2.25,2.00,1.85,39.0,2.00,NaN,NaN,NaN,0,1,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,45.0,0.0,0.0,1.0,3.0,63.0,185.0,0.0,0.0,1.0,3.0,6.0,8.0,32.770916,2.333333,1.066667,2.333333,0.500000,1.558333,0.0,0.60,0.6,0.0,0.0,0.0,1.500000,0.385714,8.845000,19.5,1.875,1.600000,0.000000,21.25
4,4,2,29.0,1,P002,3.066667,4.238095,4.000000,3.571429,4.428571,4.285714,4.714286,4.428571,2.75,1.25,2.50,2.75,2.75,2.40,22.0,2.75,0.666667,0.571429,100.0,0,1,2,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,45.0,0.0,0.0,1.0,3.0,63.0,185.0,0.0,0.0,1.0,3.0,6.0,8.0,32.770916,2.333333,1.066667,2.333333,0.500000,1.558333,0.0,0.60,0.6,0.0,0.0,0.0,1.500000,0.385714,8.845000,19.5,1.875,1.600000,0.000000,21.25

In [23]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.preprocessing import StandardScaler

df = df_final.copy()

# Always keep these columns
id_cols = ['AnonID', 'Phase']

# Identify post-only variables (only appropriate for Phase 2)
post_only_cols = [col for col in df.columns if any(prefix in col for prefix in ['CEQ30_', 'MEQ30_', '5DASC_'])]

# Identify columns that should always be labeled DEMO_ regardless of phase
demo_only_cols = [
    col for col in df.columns
    if any(sub in col for sub in [
        'Session', 'Private_or_group', 'Vomit_', 'BM_', 'Fainting_',
        'Rapeh_', 'Sananga_', 'Age', 'Sex', 'Gender', 'Education',
        'Income', 'Height_in', 'Weight_lb', 'Lyme_DX', 'Post_Lyme_DX',
        'Psychedelic_Use', 'Cannabis_Use', 'Nervous', 'Excited', 'BMI', 'Days btwn', 'Autoimmu'
    ])
]

# Prepare phase-wise containers
phase_dfs = {}

for phase in [1, 2, 3]:
    df_phase = df[df['Phase'] == phase].copy()

    # Drop post-only data for Phases 1 and 3
    if phase != 2:
        df_phase = df_phase.drop(columns=post_only_cols, errors='ignore')

    # Tag columns with temporal prefix/suffix
    for col in df_phase.columns:
        if col in id_cols:
            continue
        if col in demo_only_cols:
            df_phase.rename(columns={col: f"DEMO_{col}"}, inplace=True)
        elif phase == 1:
            df_phase.rename(columns={col: f"PRE_{col}"}, inplace=True)
        elif phase == 2:
            df_phase.rename(columns={col: f"{col}_POST"}, inplace=True)
        elif phase == 3:
            df_phase.rename(columns={col: f"{col}_3MONTHSPOST"}, inplace=True)

    phase_dfs[phase] = df_phase



# Define imputation function
def impute_phase(df_phase):
    ids = df_phase[id_cols].reset_index(drop=True)
    numeric = df_phase.drop(columns=id_cols).select_dtypes(include=['float64', 'int64'])
    missing_before = numeric.isnull().sum()
    scaler = StandardScaler()
    scaled = pd.DataFrame(scaler.fit_transform(numeric), columns=numeric.columns)

    imputer = IterativeImputer(random_state=42, max_iter=10)
    imputed_array = imputer.fit_transform(scaled)

    # Only keep columns that actually have at least 1 non-missing value
    valid_cols = numeric.columns[numeric.notnull().any()].tolist()
    # After imputation, imputed_array.shape[1] == len(valid_cols)
    imputed = pd.DataFrame(imputed_array, columns=valid_cols)
    missing_after = imputed.isnull().sum()
    print("Missing per column before:", missing_before)
    print("Missing per column after:", missing_after)
    impute_fraction = (missing_before / len(numeric)).sort_values(ascending=False)
    print(impute_fraction)

    # Use only valid_cols for inverse transform
    unscaled = pd.DataFrame(
        scaler.inverse_transform(imputed.reindex(columns=scaled.columns, fill_value=0)),  # fill_value can be 0 or np.nan
        columns=scaled.columns
    )
    # If some columns were fully-missing, fill with NaN
    for col in scaled.columns:
        if col not in valid_cols:
            unscaled[col] = np.nan
    # Reorder columns (if needed)
    unscaled = unscaled[scaled.columns]

    return pd.concat([ids, unscaled], axis=1)

# Run and combine imputed phases
imputed_phases = [impute_phase(phase_dfs[p]) for p in [1, 2, 3]]
df_imputed_final = pd.concat(imputed_phases, axis=0).sort_values(by=['AnonID', 'Phase'])
columns_to_drop = ['PRE_Unnamed: 0', 'Unnamed: 0_POST', 'Unnamed: 0_3MONTHSPOST']
df_imputed_final.drop(columns=columns_to_drop, inplace=True)
df_imputed_final.head()

Missing per column before: PRE_Unnamed: 0           0
DEMO_Days btwn           0
DEMO_Autoimmu            0
PRE_MAAS_Total           0
PRE_RYFF_Total           0
                        ..
DEMO_Psychedelic_Use     0
DEMO_Cannabis_Use        0
DEMO_Nervous             0
DEMO_Excited             0
DEMO_BMI                10
Length: 75, dtype: int64
Missing per column after: PRE_Unnamed: 0          0
DEMO_Days btwn          0
DEMO_Autoimmu           0
PRE_MAAS_Total          0
PRE_RYFF_Total          0
                       ..
DEMO_Psychedelic_Use    0
DEMO_Cannabis_Use       0
DEMO_Nervous            0
DEMO_Excited            0
DEMO_BMI                0
Length: 75, dtype: int64
PRE_BPI_PainReliefPercent        0.42
PRE_BPI_PainSeverityIndex        0.38
PRE_BPI_PainInterferenceIndex    0.38
DEMO_BMI                         0.20
DEMO_Height_in                   0.18
                                 ...
DEMO_Lyme_DX                     0.00
DEMO_Psychedelic_Use             0.00
DEMO_Cannabis_Use                0.00
DEMO_Nervous                     0.00
DEMO_Excited                     0.00
Length: 75, dtype: float64

/usr/local/lib/python3.11/dist-packages/sklearn/impute/_iterative.py:895: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

Missing per column before: Unnamed: 0_POST                                  0
DEMO_Days btwn                                   0
DEMO_Autoimmu                                    0
MAAS_Total_POST                                  0
RYFF_Total_POST                                  0
                                                ..
5DASC_OceanicBoundlessness_Score_POST            1
5DASC_AnxiousEgoDissolution_Score_POST           2
5DASC_VisionaryRestructuralization_Score_POST    3
5DASC_AuditoryAlterations_Score_POST             2
5DASC_ReductionOfVigilance_Score_POST            3
Length: 94, dtype: int64
Missing per column after: Unnamed: 0_POST                                  0
DEMO_Days btwn                                   0
DEMO_Autoimmu                                    0
MAAS_Total_POST                                  0
RYFF_Total_POST                                  0
                                                ..
5DASC_OceanicBoundlessness_Score_POST            0
5DASC_AnxiousEgoDissolution_Score_POST           0
5DASC_VisionaryRestructuralization_Score_POST    0
5DASC_AuditoryAlterations_Score_POST             0
5DASC_ReductionOfVigilance_Score_POST            0
Length: 94, dtype: int64
BPI_PainReliefPercent_POST        0.60
BPI_PainSeverityIndex_POST        0.56
BPI_PainInterferenceIndex_POST    0.56
DEMO_BMI                          0.20
DEMO_Height_in                    0.18
                                  ...
DEMO_Cannabis_Use                 0.00
DEMO_Lyme_DX                      0.00
DEMO_Sex                          0.00
DEMO_Post_Lyme_DX                 0.00
DEMO_Excited                      0.00
Length: 94, dtype: float64
Missing per column before: Unnamed: 0_3MONTHSPOST     0
DEMO_Days btwn             0
DEMO_Autoimmu              0
MAAS_Total_3MONTHSPOST     0
RYFF_Total_3MONTHSPOST     0
                          ..
DEMO_Psychedelic_Use       0
DEMO_Cannabis_Use          0
DEMO_Nervous               0
DEMO_Excited               0
DEMO_BMI                  10
Length: 75, dtype: int64
Missing per column after: Unnamed: 0_3MONTHSPOST    0
DEMO_Days btwn            0
DEMO_Autoimmu             0
MAAS_Total_3MONTHSPOST    0
RYFF_Total_3MONTHSPOST    0
                         ..
DEMO_Psychedelic_Use      0
DEMO_Cannabis_Use         0
DEMO_Nervous              0
DEMO_Excited              0
DEMO_BMI                  0
Length: 75, dtype: int64
BPI_PainSeverityIndex_3MONTHSPOST        0.52
BPI_PainReliefPercent_3MONTHSPOST        0.52
BPI_PainInterferenceIndex_3MONTHSPOST    0.52
DEMO_BMI                                 0.20
DEMO_Height_in                           0.18
                                         ...
DEMO_Lyme_DX                             0.00
DEMO_Psychedelic_Use                     0.00
DEMO_Cannabis_Use                        0.00
DEMO_Nervous                             0.00
DEMO_Excited                             0.00
Length: 75, dtype: float64

/usr/local/lib/python3.11/dist-packages/sklearn/impute/_iterative.py:895: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

,AnonID,Phase,DEMO_Days btwn,DEMO_Autoimmu,PRE_MAAS_Total,PRE_RYFF_Total,PRE_RYFF_Autonomy_Score,PRE_RYFF_EnvironmentalMastery_Score,PRE_RYFF_PersonalGrowth_Score,PRE_RYFF_PositiveRelations_Score,PRE_RYFF_PurposeInLife_Score,PRE_RYFF_SelfAcceptance_Score,PRE_MFI_General_Fatigue_Score,PRE_MFI_Physical_Fatigue_Score,PRE_MFI_Reduced_Activity_Score,PRE_MFI_Reduced_Motivation_Score,PRE_MFI_Mental_Fatigue_Score,PRE_MFI_TotalScore,PRE_IDS_TotalScore,PRE_SHS_TotalScore,PRE_BPI_PainSeverityIndex,PRE_BPI_PainInterferenceIndex,PRE_BPI_PainReliefPercent,DEMO_Session1_head,DEMO_Session1_neck,DEMO_Session1_thorax,DEMO_Session1_abdomen,DEMO_Session1_pelvis,DEMO_Session1_upper_extremity,DEMO_Session1_lower_extremity,DEMO_Session2_head,DEMO_Session2_neck,DEMO_Session2_thorax,DEMO_Session2_abdomen,DEMO_Session2_pelvis,DEMO_Session2_upper_extremity,DEMO_Session2_lower_extremity,DEMO_Session3_head,DEMO_Session3_neck,DEMO_Session3_thorax,DEMO_Session3_abdomen,DEMO_Session3_pelvis,DEMO_Session3_upper_extremity,DEMO_Session3_lower_extremity,DEMO_Private_or_group_1_NUM,DEMO_Private_or_group_2_NUM,DEMO_Private_or_group_3_NUM,DEMO_Vomit_1_NUM,DEMO_Vomit_2_NUM,DEMO_Vomit_3_NUM,DEMO_BM_1_NUM,DEMO_BM_2_NUM,DEMO_BM_3_NUM,DEMO_Fainting_1_NUM,DEMO_Fainting_2_NUM,DEMO_Fainting_3_NUM,DEMO_Rapeh_1_NUM,DEMO_Rapeh_2_NUM,DEMO_Rapeh_3_NUM,DEMO_Sananga_1_NUM,DEMO_Sananga_2_NUM,DEMO_Sananga_3_NUM,DEMO_Age,DEMO_Sex,DEMO_Gender,DEMO_Education,DEMO_Income,DEMO_Height_in,DEMO_Weight_lb,DEMO_Lyme_DX,DEMO_Post_Lyme_DX,DEMO_Psychedelic_Use,DEMO_Cannabis_Use,DEMO_Nervous,DEMO_Excited,DEMO_BMI,MAAS_Total_POST,RYFF_Total_POST,RYFF_Autonomy_Score_POST,RYFF_EnvironmentalMastery_Score_POST,RYFF_PersonalGrowth_Score_POST,RYFF_PositiveRelations_Score_POST,RYFF_PurposeInLife_Score_POST,RYFF_SelfAcceptance_Score_POST,MFI_General_Fatigue_Score_POST,MFI_Physical_Fatigue_Score_POST,MFI_Reduced_Activity_Score_POST,MFI_Reduced_Motivation_Score_POST,MFI_Mental_Fatigue_Score_POST,MFI_TotalScore_POST,IDS_TotalScore_POST,SHS_TotalScore_POST,BPI_PainSeverityIndex_POST,BPI_PainInterferenceIndex_POST,BPI_PainReliefPercent_POST,MEQ30_Ineffability_POST,MEQ30_MysticalExperience_POST,MEQ30_PositiveMood_POST,MEQ30_TranscendenceOfTimeAndSpace_POST,MEQ30_TotalScore_POST,CEQ30_Isolation_SUM_POST,CEQ30_Fear_SUM_POST,CEQ30_Grief_SUM_POST,CEQ30_Insanity_SUM_POST,CEQ30_Death_SUM_POST,CEQ30_Paranoia_SUM_POST,CEQ30_PhysicalDistress_SUM_POST,CEQ30_Total_SUM_POST,5DASC_TotalScore_POST,5DASC_OceanicBoundlessness_Score_POST,5DASC_AnxiousEgoDissolution_Score_POST,5DASC_VisionaryRestructuralization_Score_POST,5DASC_AuditoryAlterations_Score_POST,5DASC_ReductionOfVigilance_Score_POST,MAAS_Total_3MONTHSPOST,RYFF_Total_3MONTHSPOST,RYFF_Autonomy_Score_3MONTHSPOST,RYFF_EnvironmentalMastery_Score_3MONTHSPOST,RYFF_PersonalGrowth_Score_3MONTHSPOST,RYFF_PositiveRelations_Score_3MONTHSPOST,RYFF_PurposeInLife_Score_3MONTHSPOST,RYFF_SelfAcceptance_Score_3MONTHSPOST,MFI_General_Fatigue_Score_3MONTHSPOST,MFI_Physical_Fatigue_Score_3MONTHSPOST,MFI_Reduced_Activity_Score_3MONTHSPOST,MFI_Reduced_Motivation_Score_3MONTHSPOST,MFI_Mental_Fatigue_Score_3MONTHSPOST,MFI_TotalScore_3MONTHSPOST,IDS_TotalScore_3MONTHSPOST,SHS_TotalScore_3MONTHSPOST,BPI_PainSeverityIndex_3MONTHSPOST,BPI_PainInterferenceIndex_3MONTHSPOST,BPI_PainReliefPercent_3MONTHSPOST
0,P001,1,28.0,1.0,3.4,4.97619,5.428571,4.857143,5.857143,4.571429,4.000000,5.142857,2.25,4.25,4.25,4.00,3.0,3.55,18.0,4.5,2.333333,1.285714,90.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-6.938894e-18,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,2.775558e-17,0.0,0.0,-3.469447e-18,-3.469447e-18,0.0,1.0,1.0,1.0,1.0,1.0,1.0,28.0,0.0,0.0,3.0,2.0,63.0,119.0,0.0,6.938894e-18,1.0,2.0,6.0,8.0,21.079670,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,P001,2,28.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-6.938894e-18,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,2.775558e-17,0.0,0.0,-3.469447e-18,-3.469447e-18,0.0,1.0,1.0,1.0,1.0,1.0,1.0,28.0,0.0,0.0,3.0,2.0,63.0,119.0,0.0,6.938894e-18,1.0,2.0,6.0,8.0,21.079670,3.200000,5.536585,6.0,6.000000,6.166667,4.857143,4.571429,5.714286,2.50,4.50,4.5,4.25,3.25,3.8,13.0,5.00,4.058241,2.066249,42.829302,0.666667,1.466667,1.500000,0.666667,1.075000,0.0,0.25,0.4,0.0,0.0,0.0,1.333333,0.283333,31.253333,70.6,0.000,54.833333,10.833333,20.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,P001,3,28.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-6.938894e-18,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,2.775558e-17,0.0,0.0,-3.469447e-18,-3.469447e-18,0.0,1.0,1.0,1.0,1.0,1.0,1.0,28.0,0.0,0.0,3.0,2.0,63.0,119.0,0.0,6.938894e-18,1.0,2.0,6.0,8.0,21.079670,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.466667,4.904762,5.857143,5.285714,5.285714,5.0,4.0,4.0,3.5,4.0,3.75,4.25,3.5,3.8,11.0,5.25,1.612481,3.604362,82.042168
1,P002,1,29.0,1.0,3.6,3.97619,2.714286,2.857143,3.714286,5.000000,5.428571,4.142857,1.75,1.75,1.50,2.25,2.0,1.85,39.0,2.0,2.043551,3.252209,53.602944,0.0,1.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-6.938894e-18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.000000e+00,1.0,0.0,-3.469447e-18,-3.469447e-18,0.0,1.0,1.0,1.0,1.0,1.0,1.0,45.0,0.0,0.0,1.0,3.0,63.0,185.0,0.0,6.938894e-18,1.0,3.0,6.0,8.0,32.770916,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,P002,2,29.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-6.938894e-18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.000000e+00,1.0,0.0,-3.469447e-18,-3.469447e-18,0.0,1.0,1.0,1.0,1.0,1.0,1.0,45.0,0.0,0.0,1.0,3.0,63.0,185.0,0.0,6.938894e-18,1.0,3.0,6.0,8.0,32.770916,3.066667,4.238095,4.0,3.571429,4.428571,4.285714,4.714286,4.428571,2.75,1.25,2.5,2.75,2.75,2.4,22.0,2.75,0.666667,0.571429,100.000000,2.333333,1.066667,2.333333,0.500000,1.558333,0.0,0.60,0.6,0.0,0.0,0.0,1.500000,0.385714,8.845000,19.5,1.875,1.600000,0.000000,21.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
import pandas as pd
import numpy as np

# --- Compile missingness for each phase before imputation ---
missingness_records = []

for phase in [1, 2, 3]:
    df_phase = phase_dfs[phase]
    numeric = df_phase.drop(columns=id_cols, errors='ignore').select_dtypes(include=['float64', 'int64'])
    n_rows = len(numeric)
    missing_counts = numeric.isnull().sum()
    missing_fraction = missing_counts / n_rows
    for col in numeric.columns:
        missingness_records.append({
            "Phase": phase,
            "Variable": col,
            "N_missing": missing_counts[col],
            "N_total": n_rows,
            "Fraction_missing": missing_fraction[col]
        })

# --- Convert to DataFrame and save ---
missingness_df = pd.DataFrame(missingness_records)
missingness_df = missingness_df.sort_values(by=['Phase', 'Fraction_missing'], ascending=[True, False])

# Save to CSV locally and to Google Drive
missingness_df.to_csv("Kambo_missingness_report_by_phase.csv", index=False)
!cp Kambo_missingness_report_by_phase.csv "/content/drive/My Drive/Kambo/"

print("Saved full missingness report to Google Drive as 'Kambo_missingness_report_by_phase.csv'.")
print(missingness_df.head(20))  # Show the top 20 missing for visual QA

Saved full missingness report to Google Drive as 'Kambo_missingness_report_by_phase.csv'.
    Phase                          Variable  N_missing  N_total  \
21      1         PRE_BPI_PainReliefPercent         21       50
19      1         PRE_BPI_PainSeverityIndex         19       50
20      1     PRE_BPI_PainInterferenceIndex         19       50
74      1                          DEMO_BMI         10       50
66      1                    DEMO_Height_in          9       50
65      1                       DEMO_Income          7       50
61      1                          DEMO_Age          5       50
44      1       DEMO_Private_or_group_2_NUM          2       50
46      1                  DEMO_Vomit_1_NUM          2       50
55      1                  DEMO_Rapeh_1_NUM          2       50
11      1     PRE_MFI_General_Fatigue_Score          1       50
12      1    PRE_MFI_Physical_Fatigue_Score          1       50
13      1    PRE_MFI_Reduced_Activity_Score          1       50
14      1  PRE_MFI_Reduced_Motivation_Score          1       50
15      1      PRE_MFI_Mental_Fatigue_Score          1       50
16      1                PRE_MFI_TotalScore          1       50
18      1                PRE_SHS_TotalScore          1       50
43      1       DEMO_Private_or_group_1_NUM          1       50
45      1       DEMO_Private_or_group_3_NUM          1       50
47      1                  DEMO_Vomit_2_NUM          1       50

    Fraction_missing
21              0.42
19              0.38
20              0.38
74              0.20
66              0.18
65              0.14
61              0.10
44              0.04
46              0.04
55              0.04
11              0.02
12              0.02
13              0.02
14              0.02
15              0.02
16              0.02
18              0.02
43              0.02
45              0.02
47              0.02

In [24]:
import os

# Mount Google Drive
from google.colab import drive

df_imputed_final.to_csv('Kambo_imputed.csv')
!cp Kambo_imputed.csv "/content/drive/My Drive/Kambo/"